/**
 * seed.js — the §5.2 sandbox seed for the SYNTHETIC nouns (PortOrder,
 * CoverageRecord, UsageRecord). EVERY record here is synthetic and labeled:
 * fictional carriers and subscribers, fictional addresses, no real
 * identifiers — every telephone number sits in the NANP fictional
 * 555-01XX range, SPID-shaped ids spell EXAMPLE, OCN-shaped ids use the
 * X99- pattern no real OCN uses, and every record carries `example: true`.
 *
 * (The NumberingResource noun is NOT here: it is REAL ingested public data —
 * seed-numbering.js, generated by scripts/ingest-numbering.mjs from the
 * NANPA NPA report with provenance on the corpus. Real data is never labeled
 * example; synthetic data always is.)
 *
 * Internal consistency is a property of the generator, not of hand-typed
 * rows: port-order status derives from its FOC date against a fixed AS_OF
 * date, every UsageRecord references a subscriber number that a completed
 * port order carried in, every synthetic number's NPA is a real in-service
 * NPA from the ingested corpus (the two plies tie), and the usage cycle
 * summary equals the sum of its rated events by construction — the way a
 * premium reseller back-office example must.
 */

export const AS_OF = "2026-08-23"; // fixed — the seed is deterministic, never Date.now()

export const EXAMPLE_NOTE =
  "Example data — synthetic sandbox seed over fictional carriers (Harborline Communications LLC, " +
  "Kestrel Mobile Cooperative, Draywick Networks Inc — all fictional). No real carrier, subscriber, " +
  "SPID, OCN, address, or telephone number appears in the synthetic corpus: every number sits in the " +
  "NANP fictional 555-01XX range, SPID-shaped ids spell EXAMPLE, and OCN-shaped ids use the X99- " +
  "pattern. Anonymous sandbox: stateless reads; nothing you send is stored at wave zero; the seed " +
  "regenerates on every deploy.";

/** The fictional parties of the reseller back office (the OSS/BSS tenant + counterparties). */
export const carriers = [
  {
    $type: "Organization",
    id: "car_harborline",
    name: "Harborline Communications LLC (fictional)",
    kind: "MVNO — the sandbox tenant",
    spid: "EXAMPLE1",
    ocn: "X991",
    example: true,
  },
  {
    $type: "Organization",
    id: "car_kestrel",
    name: "Kestrel Mobile Cooperative (fictional)",
    kind: "regional wireless reseller — losing carrier in the port examples",
    spid: "EXAMPLE2",
    ocn: "X992",
    example: true,
  },
  {
    $type: "Organization",
    id: "car_draywick",
    name: "Draywick Networks Inc (fictional)",
    kind: "fiber overbuilder — the coverage-record operator",
    spid: "EXAMPLE3",
    ocn: "X993",
    example: true,
  },
];

/** Days between AS_OF and an ISO date (positive = future). */
function daysFromAsOf(iso) {
  return Math.round((Date.parse(iso) - Date.parse(AS_OF)) / 86400000);
}

/** LNP status derives from the FOC date — never hand-typed. */
function statusFor(focAt) {
  if (!focAt) return "requested";
  const d = daysFromAsOf(focAt);
  if (d > 0) return "foc-issued"; // FOC in the future: committed, not yet activated
  return "completed"; // FOC in the past: the number activated on the gaining network
}

/** One port order: one subscriber number moving carriers under an LOA. */
function port(seq, number, direction, losingCarrierId, gainingCarrierId, requestedAt, focAt, extra = {}) {
  const losing = carriers.find((c) => c.id === losingCarrierId);
  const gaining = carriers.find((c) => c.id === gainingCarrierId);
  return {
    $type: "PortOrder",
    id: `prt_${String(seq).padStart(2, "0")}`,
    subscriberNumber: number, // NANP fictional range: NPA-555-01XX
    npa: number.slice(2, 5),
    direction, // port-in | port-out (relative to the sandbox tenant, Harborline)
    losingCarrierId,
    losingCarrier: losing.name,
    losingSpid: losing.spid,
    gainingCarrierId,
    gainingCarrier: gaining.name,
    gainingSpid: gaining.spid,
    loa: { id: `loa_${String(seq).padStart(2, "0")}`, signedAt: requestedAt, authorizer: "example subscriber (fictional)" },
    requestedAt,
    ...(focAt && { focAt }),
    status: statusFor(focAt),
    asOf: AS_OF,
    ...extra,
    example: true,
    exampleNote: EXAMPLE_NOTE,
  };
}

/** The port-order corpus — a full LNP working set for the sandbox tenant:
 *  completed ports (their numbers carry the usage), a committed FOC, a
 *  fresh request, and one port-out. */
export const portOrders = [
  port(1, "+12015550100", "port-in", "car_kestrel", "car_harborline", "2026-06-02", "2026-06-09"),
  port(2, "+12145550142", "port-in", "car_kestrel", "car_harborline", "2026-06-15", "2026-06-22"),
  port(3, "+13125550177", "port-in", "car_kestrel", "car_harborline", "2026-07-01", "2026-07-08"),
  port(4, "+14155550163", "port-in", "car_kestrel", "car_harborline", "2026-08-11", "2026-09-02", {
    note: "FOC committed for 2026-09-02 — activation pending",
  }),
  port(5, "+15125550131", "port-in", "car_kestrel", "car_harborline", "2026-08-20", undefined, {
    note: "LSR submitted; awaiting FOC from the losing carrier",
  }),
  port(6, "+16045550119", "port-out", "car_harborline", "car_kestrel", "2026-07-28", "2026-08-04"),
];

/** Coverage records — serviceability at the address grain (fictional
 *  addresses; `served` derives from technology, never hand-typed). */
const coverage = (seq, address, npa, technology, downMbps, upMbps) => ({
  $type: "CoverageRecord",
  id: `cov_${String(seq).padStart(2, "0")}`,
  operatorId: "car_draywick",
  operator: carriers[2].name,
  address: `${address} (fictional address)`,
  npa,
  technology,
  downMbps,
  upMbps,
  served: technology !== "none",
  asOf: AS_OF,
  example: true,
  exampleNote: EXAMPLE_NOTE,
});

export const coverageRecords = [
  coverage(1, "11 Fennett Row", "201", "fiber-xgs-pon", 5000, 5000),
  coverage(2, "42 Cordwainer Street", "214", "fiber-gpon", 1000, 1000),
  coverage(3, "7 Bricklight Yard", "312", "fixed-wireless", 300, 50),
  coverage(4, "89 Larkmoor Bend", "415", "dsl-legacy", 25, 3),
  coverage(5, "230 Quarry Hollow Road", "512", "none", 0, 0),
];

/** Rated usage events (CDR grain) — only for numbers a COMPLETED port-in
 *  carried onto the tenant's network; cycle 2026-08. */
const usageEvent = (seq, number, kind, quantity, unit, ratedUsd, at) => ({
  $type: "UsageRecord",
  id: `usg_${String(seq).padStart(2, "0")}`,
  subscriberNumber: number,
  cycle: "2026-08",
  kind, // voice | sms | data
  quantity,
  unit,
  ratedUsd,
  at,
  example: true,
  exampleNote: EXAMPLE_NOTE,
});

export const usageRecords = [
  usageEvent(1, "+12015550100", "voice", 42, "minutes", 0.84, "2026-08-03T14:22:00Z"),
  usageEvent(2, "+12015550100", "data", 2.4, "GB", 1.2, "2026-08-07T09:10:00Z"),
  usageEvent(3, "+12015550100", "sms", 118, "messages", 0.59, "2026-08-12T18:45:00Z"),
  usageEvent(4, "+12145550142", "voice", 187, "minutes", 3.74, "2026-08-05T11:02:00Z"),
  usageEvent(5, "+12145550142", "data", 11.8, "GB", 5.9, "2026-08-15T21:33:00Z"),
  usageEvent(6, "+13125550177", "data", 6.1, "GB", 3.05, "2026-08-18T07:54:00Z"),
];

const round2 = (n) => Math.round(n * 100) / 100;

/** The cycle summary DERIVES from the events — the BSS ledger ties by construction. */
export const usageCycleSummary = {
  $type: "UsageCycleSummary",
  id: "usg_cycle_2026-08",
  cycle: "2026-08",
  tenantId: "car_harborline",
  tenant: carriers[0].name,
  subscribers: [...new Set(usageRecords.map((u) => u.subscriberNumber))].length,
  events: usageRecords.length,
  totalRatedUsd: round2(usageRecords.reduce((s, u) => s + u.ratedUsd, 0)),
  example: true,
  exampleNote: EXAMPLE_NOTE,
};

export function getPortOrder(id) {
  return portOrders.find((x) => x.id === id);
}

export function getCoverageRecord(id) {
  return coverageRecords.find((x) => x.id === id);
}

export function getUsageRecord(id) {
  if (id === usageCycleSummary.id) return usageCycleSummary;
  return usageRecords.find((x) => x.id === id);
}
