/**
 * worker.js — telecom, wave zero (register row telecom, TRUE-ZERO GAP;
 * serving at the row-key placeholder address telecom.org.ai).
 *
 * One substrate, two plies from ONE manifest (template spec §3): the data
 * face (/port-orders, /numbering-resources, /coverage-records,
 * /usage-records — typed records from the row's schemas, the
 * NumberingResource corpus REAL and provenance-labeled) and the headless
 * face (the same collections as the reseller OSS/BSS system door at the
 * register's — UNVERIFIED — OSS/BSS coordinate, plus the per-outcome port
 * verb). There is no second API. The MCP door (/mcp) serves the same
 * operations from the same definitions.
 *
 * The AXP quartet + branching collection + conneg home are generated by the
 * vendored axp-faces@0.3.0 (PINS.json digest) — never hand-rolled; the four
 * axp-ext-rates-g2 fields (rates[], g2, links.verify, operationId) are
 * emitted NATIVELY by the generator from the manifest — no bridge layer
 * exists in this property. This file only composes and adds the extra live
 * doors the manifest declares.
 */

import { ok, empty, envelopeResponse, offer, createAxpRoutes } from "./axp/index.js";
import { manifest, icpDoc } from "./manifest.js";
import { mcpHandler } from "./mcp.js";
import { coverageRecords, usageRecords, usageCycleSummary, getPortOrder, getCoverageRecord, getUsageRecord, EXAMPLE_NOTE } from "./seed.js";
import { numberingResources, NUMBERING_PROVENANCE, getNumberingResource } from "./seed-numbering.js";
import { verifyRoutes } from "./verify.js";
import { emitMeter, emitReceipt, emitSignal } from "./seams.js";

const JSON_CT = { "content-type": "application/json; charset=utf-8" };

function json(obj, { status = 200, head = false } = {}) {
  return new Response(head ? null : JSON.stringify(obj, null, 2), { status, headers: JSON_CT });
}

const generatorRoutes = createAxpRoutes(manifest);

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const head = request.method === "HEAD";

    // ── the MCP door (same operations, second transport) ─────────────────────
    const mcpHit = await mcpHandler(request, env);
    if (mcpHit !== undefined) return mcpHit;

    // ── the machine face — the vendored generator, native extension fields ───
    const hit = await generatorRoutes(request, env);
    if (hit !== undefined) {
      if (path === manifest.collection.path) emitMeter(env, { operation: "listPortOrders" });
      if (path === "/" || path === "/index.html") emitSignal(env, request, { surface: "home" });
      return hit;
    }

    // ── extra live doors (every one declared in the manifest routes) ─────────
    if (request.method === "GET" || head) {
      const prtMatch = path.match(/^\/port-orders\/([A-Za-z0-9_.-]+)$/);
      if (prtMatch) {
        emitMeter(env, { operation: "getPortOrder" });
        const portOrder = getPortOrder(prtMatch[1]);
        if (!portOrder)
          return json(empty(`no port order '${prtMatch[1]}' is visible to this caller — an honest miss, not an error page`, { memberName: "portOrders" }), { status: 404, head });
        return json({ type: "OK", portOrder }, { head });
      }

      if (path === "/numbering-resources") {
        emitMeter(env, { operation: "listNumberingResources" });
        const npa = url.searchParams.get("npa");
        const location = url.searchParams.get("location");
        const rows = numberingResources
          .filter((r) => (npa ? r.npa === npa : true))
          .filter((r) => (location ? r.location === location : true));
        if (rows.length === 0)
          return json(empty(`no numbering resources match the filter — a truthful empty set, not an error`, { memberName: "numberingResources" }), { head });
        return json(ok(rows, { memberName: "numberingResources", extra: { provenance: NUMBERING_PROVENANCE } }), { head });
      }

      const npaMatch = path.match(/^\/numbering-resources\/([A-Za-z0-9_.-]+)$/);
      if (npaMatch) {
        emitMeter(env, { operation: "getNumberingResource" });
        const numberingResource = getNumberingResource(npaMatch[1]);
        if (!numberingResource)
          return json(empty(`no numbering resource '${npaMatch[1]}' is in the ingested corpus — see /numbering-resources for the corpus and its provenance`, { memberName: "numberingResources" }), { status: 404, head });
        return json({ type: "OK", numberingResource, provenance: NUMBERING_PROVENANCE }, { head });
      }

      if (path === "/coverage-records") {
        emitMeter(env, { operation: "listCoverageRecords" });
        const technology = url.searchParams.get("technology");
        const rows = technology ? coverageRecords.filter((c) => c.technology === technology) : coverageRecords;
        if (rows.length === 0)
          return json(empty(`no coverage records match technology=${technology} — a truthful empty set, not an error`, { memberName: "coverageRecords" }), { head });
        return json(ok(rows, { memberName: "coverageRecords" }), { head });
      }

      const covMatch = path.match(/^\/coverage-records\/([A-Za-z0-9_.-]+)$/);
      if (covMatch) {
        emitMeter(env, { operation: "getCoverageRecord" });
        const coverageRecord = getCoverageRecord(covMatch[1]);
        if (!coverageRecord) return json(empty(`no coverage record '${covMatch[1]}' exists in this workspace`, { memberName: "coverageRecords" }), { status: 404, head });
        return json({ type: "OK", coverageRecord }, { head });
      }

      if (path === "/usage-records") {
        emitMeter(env, { operation: "listUsageRecords" });
        const kind = url.searchParams.get("kind");
        const subscriberNumber = url.searchParams.get("subscriberNumber");
        const rows = usageRecords
          .filter((u) => (kind ? u.kind === kind : true))
          .filter((u) => (subscriberNumber ? u.subscriberNumber === subscriberNumber : true));
        if (rows.length === 0)
          return json(empty(`no usage records match the filter — a truthful empty set, not an error`, { memberName: "usageRecords" }), { head });
        return json(ok(rows, { memberName: "usageRecords", extra: { cycleSummary: usageCycleSummary } }), { head });
      }

      const usgMatch = path.match(/^\/usage-records\/([A-Za-z0-9_.-]+)$/);
      if (usgMatch) {
        emitMeter(env, { operation: "getUsageRecord" });
        const usageRecord = getUsageRecord(usgMatch[1]);
        if (!usageRecord) return json(empty(`no usage record '${usgMatch[1]}' exists in this workspace`, { memberName: "usageRecords" }), { status: 404, head });
        return json({ type: "OK", usageRecord }, { head });
      }

      if (path === "/icp.json") {
        // the G2 document the card's g2 member mirrors (links.icp / icpUrl)
        return json(icpDoc, { head });
      }

      if (path === "/healthz") return json(ok([{ status: "ok", sandbox: "anon", note: EXAMPLE_NOTE }]), { head });

      const v = await verifyRoutes(request, url);
      if (v !== undefined) return v;
    }

    // ── the per-outcome port door: a typed 402 OFFER; wave-zero labeled stub ──
    if (path === "/ports" && request.method === "POST") {
      emitMeter(env, { operation: "orderNumberPort", shape: "paid-402" });
      emitReceipt(env, { operation: "orderNumberPort", offerId: "number-port-outcome" });
      return envelopeResponse(
        offer({
          ...manifest.pricing.offers[0],
          message:
            "Ordering a completed, verified number port is the payable outcome door. Wave zero is " +
            "test-mode: this 402 is a labeled stub — no billing occurs. The alternatives list only mounted " +
            "rungs: the free keyless sandbox floor, or the pay rung (stub).",
        }),
        { status: 402 },
      );
    }

    return envelopeResponse(
      empty(`nothing is served at ${request.method} ${path} — the contract at /openapi.json lists every live door`),
      { status: 404 },
    );
  },
};
