/**
 * worker.js — the fn-corporate-affairs wave-zero property: one Workers-shaped
 * fetch handler serving BOTH plies from ONE definition (template spec §3):
 *
 *   data face      GET /stakeholders (branching collection), /stakeholders/{id},
 *                  /engagements, /engagements/{id}, /mentions, /mentions/{id},
 *                  /disclosures, /disclosures/{id}
 *   headless face  POST /stakeholders, POST /engagements — system-of-record
 *                  verbs on the SAME collections, same envelopes (the
 *                  stakeholder/IR-CRM system)
 *   machine face   the AXP quartet + probes, generated by the vendored
 *                  axp-faces (pinned apis-ax-axp@2.6.0) — never hand-rolled
 *   MCP door       POST /mcp — the same Nouns/verbs over JSON-RPC (one
 *                  definition); authless: the anon-sandbox rung is the only
 *                  mounted rung (bearer-key applies to rungs above, unmounted)
 *   verify         GET /verify, /verify/suite.json — "run our tests"
 *   icp            GET /icp.json — the G2 coordinates + agent classes
 *
 * RULED EXTENSION PLACEMENTS (batch-2 rollup — binding; bridges EXACTLY here
 * until the upstream axp-faces re-vendor lands; the vendored bytes are never
 * edited):
 *   - `rates[]` TOP-LEVEL on the Pricing Document (operationId-keyed, every
 *     row freeQuota or zero price) — /pricing intercepted below;
 *   - `g2` TOP-LEVEL on the card — agents.json intercepted below;
 *   - `links.verify` as a card link member — same interception;
 *   - `operationId` on EVERY route — /openapi.json intercepted below.
 *
 * WAVE-ZERO HONESTY, stated once and enforced below:
 *   - every record is labeled synthetic example data (see ./seed.js);
 *   - mutations are per-isolate and ephemeral (disclosed on every response);
 *   - the rate card is a stub (binding: false + statement); the 402 OFFER
 *     boundary is real and probeable, but nothing settles and nothing charges;
 *   - the OFFER advertises ONLY the mounted sandbox rung (batch-2 rule);
 *   - seams (metering / money / traffic events) are EMITTED per template §7.4
 *     — structured events tagged {substrate, projection, motion, operation,
 *     shape, pattern} — but no dashboard, billing, or account surface exists
 *     here, by design.
 */

import { createAxpRoutes } from './axp/routes.js'
import { buildCard } from './axp/card.js'
import { buildOpenapi } from './axp/openapi.js'
import { buildPricingDocument } from './axp/pricing.js'
import { envelopeResponse, ok, empty } from './axp/envelope.js'
import { negotiate, serveFace, AGENT_UA_TOKENS } from './axp/conneg.js'
import { manifest, ORIGIN } from './manifest.js'
import { stakeholders, engagements, mentions, disclosures } from './seed.js'
import { seamTags } from './substrate.js'

const RETENTION = 'ephemeral — per-isolate memory only; no durability at wave zero'

// ── the G2 block (spec §2; ruled top-level card member) ─────────────────────
const g2 = {
  icp: {
    companyTypes: [
      'public companies, regulated enterprises, trade associations — the row flag is carried verbatim: buyer distribution skews furthest from the estate SMB/agent-native center of mass [UNVERIFIED inference]',
    ],
    jobTypes: ['communications director', 'investor-relations officer', 'government-relations lead', 'corporate secretary'],
  },
  coordinates: ['Function=CorporateAffairs', 'Department=Communications/IR/GovRelations'],
  personas: [
    { id: 'comms-director', description: 'communications/PR lead running the press and mention register' },
    { id: 'ir-officer', description: 'investor-relations officer running the investor stakeholder and disclosure cadence' },
    { id: 'gov-relations-lead', description: 'government-relations/corporate-secretary role managing regulator engagements' },
    { id: 'agent-caller', description: 'autonomous agent consuming stakeholder/engagement/mention/disclosure records over this machine face (B2A)' },
  ],
}

// ── the card: generator truth + ruled bridges (g2 top-level, links.verify) ──
// The vendored generator does not yet emit links.verify or a g2 member; the
// batch-2 rollup rules their placement (top-level g2; links.verify as a card
// link member). Additive extension of the GENERATED card — the quartet itself
// stays generator-emitted, and the gap is carried upstream as a generator
// issue (fix-the-generator law), never patched deeper than these members.
const card = (() => {
  const c = buildCard(manifest)
  return { ...c, g2, links: { ...c.links, verify: `${ORIGIN}/verify` } }
})()

// ── openapi: generator truth + operationId on EVERY route (ruled bridge) ────
// The vendored buildOpenapi emits operationIds for its own quartet routes
// (listCollection, getPricing, getOffer) but not for manifest routes. The
// batch-2 rollup rules operationId on every route; assigned here additively
// on the generated document. rates[].operation ⊆ these ids (§9.1).
const ROUTE_OPERATION_IDS = {
  'GET /stakeholders/{stakeholderId}': 'getStakeholder',
  'POST /stakeholders': 'createStakeholder',
  'GET /engagements': 'listEngagements',
  'GET /engagements/{engagementId}': 'getEngagement',
  'POST /engagements': 'logEngagement',
  'GET /mentions': 'listMentions',
  'GET /mentions/{mentionId}': 'getMention',
  'GET /disclosures': 'listDisclosures',
  'GET /disclosures/{disclosureId}': 'getDisclosure',
  'GET /icp.json': 'getIcp',
  'GET /verify': 'getVerify',
  'GET /verify/suite.json': 'getVerifySuite',
}
const openapiDoc = (() => {
  const doc = buildOpenapi(manifest)
  const paths = {}
  for (const [p, methods] of Object.entries(doc.paths)) {
    paths[p] = {}
    for (const [m, op] of Object.entries(methods)) {
      const key = `${m.toUpperCase()} ${p}`
      paths[p][m] = op.operationId !== undefined ? op : { operationId: ROUTE_OPERATION_IDS[key], ...op }
    }
  }
  return { ...doc, paths }
})()

// ── pricing: generator truth + rates[] TOP-LEVEL (ruled bridge) ─────────────
// Every row keys an OpenAPI operationId and carries freeQuota or a zero
// price (§9.1). Stub character inherited from the document's binding:false
// + statement — no live settlement exists.
const pricingDoc = {
  ...buildPricingDocument(manifest),
  rates: [
    { operation: 'listCollection', price: 0, unit: 'usd', freeQuota: 'unlimited', note: 'the branching /stakeholders collection — free, keyless (anon-sandbox floor)' },
    { operation: 'getStakeholder', price: 0.002, unit: 'usd', freeQuota: 100 },
    { operation: 'createStakeholder', price: 0.002, unit: 'usd', freeQuota: 100 },
    { operation: 'listEngagements', price: 0, unit: 'usd', freeQuota: 'unlimited' },
    { operation: 'getEngagement', price: 0.002, unit: 'usd', freeQuota: 100 },
    { operation: 'logEngagement', price: 0.002, unit: 'usd', freeQuota: 100 },
    { operation: 'listMentions', price: 0, unit: 'usd', freeQuota: 'unlimited' },
    { operation: 'getMention', price: 0.002, unit: 'usd', freeQuota: 100 },
    { operation: 'listDisclosures', price: 0, unit: 'usd', freeQuota: 'unlimited' },
    { operation: 'getDisclosure', price: 0.002, unit: 'usd', freeQuota: 100 },
  ],
}
const pricingFaces = (() => {
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const title = `${manifest.name} — pricing`
  return {
    json: pricingDoc,
    md: `# ${title}\n\n\`\`\`json\n${JSON.stringify(pricingDoc, null, 2)}\n\`\`\`\n`,
    html: `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><title>${esc(title)}</title></head>\n<body><h1>${esc(title)}</h1><pre>${esc(JSON.stringify(pricingDoc, null, 2))}</pre></body></html>\n`,
  }
})()

const axp = createAxpRoutes(manifest)

// ── per-isolate state (the auto-minted anon workspace, §5.2/#17) ────────────
const state = {
  stakeholders: new Map(stakeholders.map((s) => [s.id, structuredClone(s)])),
  engagements: new Map(engagements.map((e) => [e.id, structuredClone(e)])),
  mentions: new Map(mentions.map((m) => [m.id, structuredClone(m)])),
  disclosures: new Map(disclosures.map((d) => [d.id, structuredClone(d)])),
  minted: 0,
}

// ── seams (template §7.4 — emitted, never rendered; no account UI here) ────
function emitSeam(env, event) {
  const line = JSON.stringify({ ...seamTags, ts: new Date().toISOString(), ...event })
  // Wave zero: structured stdout is the seam. A queue binding, when one is
  // attached, receives the same event without a shape change. (In-process
  // test harnesses set globalThis.__SEAM_SILENT to keep their output legible;
  // the events still shape-check because emitSeam still constructs them.)
  if (globalThis.__SEAM_SILENT !== true) console.log(line)
  if (env && env.SEAMS && typeof env.SEAMS.send === 'function') {
    try {
      env.SEAMS.send(JSON.parse(line))
    } catch {
      /* the seam is best-effort transport, never a request failure */
    }
  }
}

function identityClass(request) {
  // id.org.ai grain is not wired at wave zero — only the CLASS is derivable.
  const mode = request.headers.get('sec-fetch-mode')
  const dest = request.headers.get('sec-fetch-dest')
  if (mode === 'navigate' || dest === 'document') return 'human-browser'
  const ua = (request.headers.get('user-agent') || '').toLowerCase()
  if (AGENT_UA_TOKENS.some((t) => ua.includes(t))) return 'machine-agent'
  return 'machine-unattributed'
}

// ── three-faced serving for this worker's own GET addresses ────────────────
function threeFaces(title, obj) {
  const json = obj
  const md = `# ${title}\n\n\`\`\`json\n${JSON.stringify(obj, null, 2)}\n\`\`\`\n`
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const html = `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><title>${esc(title)}</title></head>\n<body><h1>${esc(title)}</h1><pre>${esc(JSON.stringify(obj, null, 2))}</pre></body></html>\n`
  return { json, md, html }
}

// ── the ICP document: the row's G2 coordinates, exposed ─────────────────────
const icpDocument = {
  $context: 'https://schema.org.ai',
  property: 'fn-corporate-affairs.org.ai',
  substrate: 'fn-corporate-affairs',
  g2,
  system: { system: 'StakeholderRelations', coordinates: g2.coordinates },
  agent_classes: [
    { id: 'reader-agent', description: 'keyless reads: the quartet, /stakeholders, /engagements, /mentions, /disclosures, /verify — no key, no account' },
    {
      id: 'sandbox-transactor',
      description:
        'exercises the headless doors (POST /stakeholders, POST /engagements) against labeled synthetic state; ' +
        'mutations are per-isolate and ephemeral at wave zero',
    },
    { id: 'mcp-caller', description: 'the same Nouns and verbs over the /mcp JSON-RPC door — one definition, two transports; authless at the anon-sandbox rung' },
  ],
}

// ── the published suite (links.verify target) ───────────────────────────────
// interfaces.testSuite is deliberately NOT declared on the card: declaring it
// arms check-capability-coverage, which the deployed verifier (autonomous-qa
// 0.3.0) does not implement — a declaration today fails closed on a check the
// verifier cannot produce (the api.lawyer reference posture; batch-2 rule:
// undeclared until digest-pinned). The suite still ships and links.verify
// names it: "trust us" → "run this".
const suiteDocument = {
  $type: 'VerifySuite',
  property: 'fn-corporate-affairs.org.ai',
  version: '0.1.0',
  runner: 'node selfcheck.mjs (repo: examples/fn-corporate-affairs — fail-closed, digest-pinned)',
  pinnedSpec: 'apis-ax-axp@2.6.0',
  pinnedSpecDigest: 'a9a1197c439d708b4db54f606f07c9a2d019c7f2989fbcd9b599de2fcc028e0d',
  tests: [
    { id: 'vendored-pins', asserts: 'every vendored axp-faces file is byte-identical to its VENDORED.json digest; the PINS.json spec digest equals the ratified pin' },
    { id: 'pinned-conformance', asserts: 'gradePinned(worker) passes the pinned apis-ax-axp@2.6.0 spec (runnable view) in-process' },
    { id: 'seed-labeled', asserts: 'every seed record carries example: true and a [demo] title; fictional names only' },
    { id: 'operations-exercised', asserts: 'every declared operation answers substantively against the seed (no ghost surfaces)' },
    { id: 'ruled-placements', asserts: 'rates[] top-level on the Pricing Document (rows ⊆ operationIds, freeQuota or zero); g2 + links.verify on the card; operationId on every OpenAPI route' },
    { id: 'conneg-matrix', asserts: 'bare curl → JSON; Accept: text/markdown → md; browser navigation → HTML, on this worker’s own addresses' },
    { id: 'offer-mounted-rungs', asserts: 'the 402 OFFER advertises ONLY mounted rungs: exactly the sandbox floor at wave zero, stub character declared' },
    { id: 'head-mirrors-get', asserts: 'HEAD answers wherever GET answers, same status and headers' },
    { id: 'typed-405', asserts: 'non-GET on a GET-only AXP address answers a typed BLOCKED envelope with Allow' },
  ],
}

const verifyPage = {
  title: 'fn-corporate-affairs.org.ai — run our tests',
  body:
    'The published verification suite for this surface. Every claim the machine face makes is checked by a runnable test, ' +
    'not an adjective: the suite document at /verify/suite.json lists each check; the runner is selfcheck.mjs beside this ' +
    'worker in its repository, fail-closed against the pinned apis-ax-axp@2.6.0 spec (digest a9a1197c…). Independent verdict: ' +
    'https://api.qa/fn-corporate-affairs.org.ai.',
  suite: `${ORIGIN}/verify/suite.json`,
  conformance: 'https://api.qa/fn-corporate-affairs.org.ai',
}

// ── domain views (typed envelopes; the record IS the wire truth) ────────────
const listOf = (map) => [...map.values()]

function getRecord(map, id, what) {
  const rec = map.get(id)
  if (rec === undefined) return { status: 200, body: empty(`no ${what} with id ${id} — a truthful empty result, not an error`) }
  return { status: 200, body: ok([rec]) }
}

// ── MCP (same definition, JSON-RPC transport; authless — sandbox rung only) ─
const mcpTools = {
  listStakeholders: {
    description: 'List stakeholders; optional filters type, status (labeled demo seed)',
    input: { type: 'string?', status: 'string?' },
    call: (a) => listOf(state.stakeholders).filter((s) => (a.type ? s.type === a.type : true) && (a.status ? s.status === a.status : true)),
  },
  getStakeholder: { description: 'Get one stakeholder by id', input: { stakeholderId: 'string' }, call: (a) => state.stakeholders.get(String(a.stakeholderId)) ?? null },
  listEngagements: { description: 'List the engagement log (labeled demo seed)', input: {}, call: () => listOf(state.engagements) },
  getEngagement: { description: 'Get one engagement by id', input: { engagementId: 'string' }, call: (a) => state.engagements.get(String(a.engagementId)) ?? null },
  listMentions: { description: 'List press-mention records (labeled demo seed)', input: {}, call: () => listOf(state.mentions) },
  getMention: { description: 'Get one mention by id', input: { mentionId: 'string' }, call: (a) => state.mentions.get(String(a.mentionId)) ?? null },
  listDisclosures: { description: 'List the federated disclosure view (labeled synthetic stand-ins)', input: {}, call: () => listOf(state.disclosures) },
  getDisclosure: { description: 'Get one disclosure by id', input: { disclosureId: 'string' }, call: (a) => state.disclosures.get(String(a.disclosureId)) ?? null },
}

function mcpResponse(id, result) {
  return new Response(JSON.stringify({ jsonrpc: '2.0', id, result }), { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } })
}
function mcpError(id, code, message) {
  return new Response(JSON.stringify({ jsonrpc: '2.0', id, error: { code, message } }), { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } })
}

async function handleMcp(request, env) {
  let msg
  try {
    msg = await request.json()
  } catch {
    return mcpError(null, -32700, 'parse error — the /mcp door speaks JSON-RPC 2.0')
  }
  const { id = null, method, params = {} } = msg || {}
  if (method === 'initialize') {
    return mcpResponse(id, {
      protocolVersion: '2024-11-05',
      capabilities: { tools: {} },
      serverInfo: { name: 'fn-corporate-affairs.org.ai', version: '0.1.0' },
    })
  }
  if (method === 'notifications/initialized') return new Response(null, { status: 202 })
  if (method === 'tools/list') {
    return mcpResponse(id, {
      tools: Object.entries(mcpTools).map(([name, t]) => ({
        name,
        description: t.description,
        inputSchema: { type: 'object', properties: Object.fromEntries(Object.entries(t.input).map(([k, v]) => [k, { type: String(v).replace('?', '') }])) },
      })),
    })
  }
  if (method === 'tools/call') {
    const tool = mcpTools[params.name]
    if (!tool) return mcpError(id, -32602, `unknown tool ${JSON.stringify(params.name)} — tools/list names every tool that exists`)
    emitSeam(env, { seam: 'meter', operation: params.name, shape: 'anon-sandbox', transport: 'mcp' })
    const result = tool.call(params.arguments || {})
    return mcpResponse(id, { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }], isError: false })
  }
  return mcpError(id, -32601, `method ${JSON.stringify(method)} is not served — this door answers initialize, tools/list, tools/call`)
}

// ── router ──────────────────────────────────────────────────────────────────
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const path = url.pathname
    const method = request.method

    emitSeam(env, {
      seam: 'traffic',
      path,
      method,
      identity: null, // id.org.ai grain not wired at wave zero — class only
      identityClass: identityClass(request),
      referral: request.headers.get('referer') || null,
    })

    // 1. the card, extended per the ruled placements (g2 + links.verify)
    if (path === '/.well-known/agents.json' && (method === 'GET' || method === 'HEAD')) {
      return new Response(method === 'HEAD' ? null : JSON.stringify(card, null, 2), {
        status: 200,
        headers: { 'content-type': 'application/json; charset=utf-8' },
      })
    }

    // 2. openapi, extended per the ruled placement (operationId on every route)
    if (path === '/openapi.json' && (method === 'GET' || method === 'HEAD')) {
      return new Response(method === 'HEAD' ? null : JSON.stringify(openapiDoc, null, 2), {
        status: 200,
        headers: { 'content-type': 'application/json; charset=utf-8' },
      })
    }
    if (path === '/openapi.json' && method !== 'GET' && method !== 'HEAD') {
      return envelopeResponse(
        { type: 'BLOCKED', reason: `method ${method} is not served at ${path} — this address answers GET and HEAD` },
        { status: 405, headers: { allow: 'GET, HEAD' } },
      )
    }

    // 3. pricing, extended per the ruled placement (rates[] top-level)
    if (path === '/pricing' || path === '/pricing.json' || path === '/pricing.md' || path === '/pricing.html') {
      if (method !== 'GET' && method !== 'HEAD') {
        return envelopeResponse(
          { type: 'BLOCKED', reason: `method ${method} is not served at ${path} — this address answers GET and HEAD` },
          { status: 405, headers: { allow: 'GET, HEAD' } },
        )
      }
      const { face } = negotiate(request, path)
      return serveFace(request, url, pricingFaces, face, { cleanPath: '/pricing' })
    }

    // 4. headless doors on collection paths BEFORE the generator (its mounted
    //    paths answer 405 to non-GET; these two POSTs are real doors)
    if (path === '/stakeholders' && method === 'POST') {
      let input
      try {
        input = await request.json()
      } catch {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the create door takes a JSON body: { title, type, interests? }' }, { status: 403 })
      }
      const TYPES = ['investor', 'regulator', 'media', 'community']
      if (!input || typeof input.title !== 'string' || !TYPES.includes(input.type)) {
        return envelopeResponse({ type: 'BLOCKED', reason: `title and type are required; type is one of ${TYPES.join(', ')} — { title, type, interests? }` }, { status: 403 })
      }
      state.minted += 1
      const rec = {
        id: `st-anon-${state.minted}`,
        $type: 'https://schema.org.ai/Stakeholder',
        example: true, // everything minted in the anon sandbox is example data by definition
        title: input.title.startsWith('[demo]') ? input.title : `[demo] ${input.title}`,
        type: input.type,
        status: 'active',
        interests: Array.isArray(input.interests) ? input.interests.map(String) : [],
        workspace: 'anon',
        retention: RETENTION,
      }
      state.stakeholders.set(rec.id, rec)
      emitSeam(env, { seam: 'meter', operation: 'createStakeholder', shape: 'anon-sandbox' })
      return envelopeResponse(ok([rec], { extra: { retention: RETENTION } }), { status: 201 })
    }

    if (path === '/engagements' && method === 'POST') {
      let input
      try {
        input = await request.json()
      } catch {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the log door takes a JSON body: { title, stakeholderId, kind, summary? }' }, { status: 403 })
      }
      if (!input || typeof input.title !== 'string' || typeof input.stakeholderId !== 'string' || typeof input.kind !== 'string') {
        return envelopeResponse({ type: 'BLOCKED', reason: 'title, stakeholderId, and kind are required — { title, stakeholderId, kind, summary? }' }, { status: 403 })
      }
      if (!state.stakeholders.has(input.stakeholderId)) {
        return envelopeResponse(empty(`no stakeholder with id ${input.stakeholderId} — a truthful empty result, not an error; list /stakeholders for live ids`))
      }
      state.minted += 1
      const rec = {
        id: `en-anon-${state.minted}`,
        $type: 'https://schema.org.ai/Engagement',
        example: true,
        title: input.title.startsWith('[demo]') ? input.title : `[demo] ${input.title}`,
        stakeholderId: input.stakeholderId,
        kind: input.kind,
        date: new Date().toISOString().slice(0, 10),
        status: 'open',
        summary: typeof input.summary === 'string' ? input.summary : null,
        workspace: 'anon',
        retention: RETENTION,
      }
      state.engagements.set(rec.id, rec)
      emitSeam(env, { seam: 'meter', operation: 'logEngagement', shape: 'anon-sandbox' })
      return envelopeResponse(ok([rec], { extra: { retention: RETENTION } }), { status: 201 })
    }

    // 5. the MCP door (authless — the anon-sandbox rung is the only mounted rung)
    if (path === '/mcp') {
      if (method !== 'POST') {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the /mcp door speaks JSON-RPC 2.0 over POST' }, { status: 405, headers: { allow: 'POST' } })
      }
      return handleMcp(request, env)
    }

    // 6. the generated machine face (branching collection, offer, llms, home)
    const hit = await axp(request, env)
    if (hit !== undefined) {
      if (path === manifest.collection.path && method === 'GET') {
        emitSeam(env, { seam: 'meter', operation: 'listStakeholders', shape: 'anon-sandbox' })
      }
      if (hit.status === 402) {
        // money seam: an OFFER was presented. Nothing settles at wave zero —
        // the event exists so the rail ledger can count the boundary.
        emitSeam(env, { seam: 'money', event: 'offer-presented', operation: path === manifest.pricing.offerPath ? 'getOffer' : 'listStakeholders', settlement: 'none — stub rate card' })
      }
      return hit
    }

    // 7. this worker's own GET addresses (conneg-served, three faces)
    if (method === 'GET' || method === 'HEAD') {
      const { face, cleanPath } = negotiate(request, path)

      const serve = (title, obj, operation, faces) => {
        if (operation) emitSeam(env, { seam: 'meter', operation, shape: 'anon-sandbox' })
        return serveFace(request, url, faces || threeFaces(title, obj), face, { cleanPath })
      }

      if (cleanPath === '/engagements') return serve('fn-corporate-affairs — engagements (labeled demo seed)', ok(listOf(state.engagements)), 'listEngagements')
      if (cleanPath === '/mentions') return serve('fn-corporate-affairs — mentions (labeled demo seed)', ok(listOf(state.mentions)), 'listMentions')
      if (cleanPath === '/disclosures')
        return serve('fn-corporate-affairs — disclosures (federated view; labeled synthetic stand-ins)', ok(listOf(state.disclosures)), 'listDisclosures')
      if (cleanPath === '/icp' || path === '/icp.json') return serve('fn-corporate-affairs — icp (G2 coordinates + agent classes)', icpDocument, null)
      if (cleanPath === '/verify') return serve('fn-corporate-affairs — run our tests', verifyPage, null)
      if (cleanPath === '/verify/suite') return serve('fn-corporate-affairs — the published suite document', suiteDocument, null)

      const stMatch = cleanPath.match(/^\/stakeholders\/([^/]+)$/)
      if (stMatch) {
        const { body } = getRecord(state.stakeholders, decodeURIComponent(stMatch[1]), 'stakeholder')
        return serve(`fn-corporate-affairs — stakeholder ${stMatch[1]}`, body, 'getStakeholder')
      }
      const enMatch = cleanPath.match(/^\/engagements\/([^/]+)$/)
      if (enMatch) {
        const { body } = getRecord(state.engagements, decodeURIComponent(enMatch[1]), 'engagement')
        return serve(`fn-corporate-affairs — engagement ${enMatch[1]}`, body, 'getEngagement')
      }
      const mnMatch = cleanPath.match(/^\/mentions\/([^/]+)$/)
      if (mnMatch) {
        const { body } = getRecord(state.mentions, decodeURIComponent(mnMatch[1]), 'mention')
        return serve(`fn-corporate-affairs — mention ${mnMatch[1]}`, body, 'getMention')
      }
      const diMatch = cleanPath.match(/^\/disclosures\/([^/]+)$/)
      if (diMatch) {
        const { body } = getRecord(state.disclosures, decodeURIComponent(diMatch[1]), 'disclosure')
        return serve(`fn-corporate-affairs — disclosure ${diMatch[1]}`, body, 'getDisclosure')
      }
    }

    // 8. typed 404 — nothing here was deleted; the route was never written
    return envelopeResponse(
      { type: 'EMPTY', results: [], message: `no route at ${path} — nothing here has been deleted; the route was never written` },
      { status: 404 },
    )
  },
}
