/**
 * seed.js — the §5.2 sandbox seed for the SYNTHETIC nouns (Booking,
 * ServiceOffer, SaleRecord). EVERY record here is synthetic and labeled:
 * one fictional salon tenant with fictional practitioners and clients,
 * fictional street names, no real identifiers — every telephone number
 * sits in the NANP fictional 555-01XX range, license-shaped ids spell
 * EXAMPLE, and every record carries `example: true`.
 *
 * (The EstablishmentLicense noun is NOT here: it is REAL ingested public
 * data — seed-licenses.js, generated by scripts/ingest-licenses.mjs from
 * the TDLR open dataset with provenance on the corpus. Real data is never
 * labeled example; synthetic data always is.)
 *
 * Internal consistency is a property of the generator, not of hand-typed
 * rows: booking status derives from the appointment time against a fixed
 * AS_OF date, every Booking references a ServiceOffer and a practitioner
 * on the menu, the booking price IS the referenced offer's price, every
 * SaleRecord settles exactly one COMPLETED booking with its line total
 * derived from the offer price, and the POS day summary equals the sum of
 * its sale records by construction — the booking ply and the POS ply tie,
 * the way a premium salon back-office example must. The synthetic salon's
 * name is checked for NON-collision against the real license corpus (a
 * fictional salon must not shadow a licensed one).
 */

export const AS_OF = "2026-08-23"; // fixed — the seed is deterministic, never Date.now()

export const EXAMPLE_NOTE =
  "Example data — synthetic sandbox seed over one fictional salon (Willowmere Salon & Day Spa — fictional; " +
  "non-collision against the real license corpus is checked at build). No real salon, practitioner, client, " +
  "license number, address, or telephone number appears in the synthetic corpus: every number sits in the " +
  "NANP fictional 555-01XX range and license-shaped ids spell EXAMPLE. Anonymous sandbox: stateless reads; " +
  "nothing you send is stored at wave zero; the seed regenerates on every deploy.";

/** The fictional salon tenant and its practitioners (booth-renter included —
 *  the register ICP's own CompanyType spread). */
export const salon = {
  $type: "Organization",
  id: "sal_willowmere",
  name: "Willowmere Salon & Day Spa (fictional)",
  kind: "full-service salon — the sandbox tenant",
  address: "14 Gorsewood Lane (fictional address)",
  telephone: "+15125550104",
  licenseRef: "EXAMPLE-LIC-0001 (fictional license-shaped id — not a TDLR number)",
  example: true,
};

export const practitioners = [
  {
    $type: "Person",
    id: "prc_01",
    name: "Maren Ostenwick (fictional)",
    role: "stylist — employee",
    licenseRef: "EXAMPLE-COS-1001",
    example: true,
  },
  {
    $type: "Person",
    id: "prc_02",
    name: "Delia Farrowmere (fictional)",
    role: "esthetician — employee",
    licenseRef: "EXAMPLE-EST-1002",
    example: true,
  },
  {
    $type: "Person",
    id: "prc_03",
    name: "Josiah Quillbrook (fictional)",
    role: "manicurist — booth renter (independent practitioner)",
    licenseRef: "EXAMPLE-MAN-1003",
    example: true,
  },
];

/** The service menu — schema.org Offer grain (8121 core: hair/nail/skin). */
const offerRow = (seq, name, category, minutes, priceUsd, practitionerId) => ({
  $type: "ServiceOffer",
  id: `svc_${String(seq).padStart(2, "0")}`,
  name,
  category, // hair | skin | nail
  minutes,
  priceUsd,
  practitionerId,
  practitioner: practitioners.find((p) => p.id === practitionerId).name,
  example: true,
  exampleNote: EXAMPLE_NOTE,
});

export const serviceOffers = [
  offerRow(1, "Women's cut & style", "hair", 60, 85, "prc_01"),
  offerRow(2, "Single-process color", "hair", 90, 120, "prc_01"),
  offerRow(3, "Classic facial", "skin", 50, 95, "prc_02"),
  offerRow(4, "Brow shaping", "skin", 20, 28, "prc_02"),
  offerRow(5, "Gel manicure", "nail", 45, 55, "prc_03"),
  offerRow(6, "Spa pedicure", "nail", 60, 70, "prc_03"),
];

/** Days between AS_OF and an ISO instant (positive = future). */
function daysFromAsOf(iso) {
  return (Date.parse(iso) - Date.parse(AS_OF + "T00:00:00Z")) / 86400000;
}

/** Booking status derives from the appointment time — never hand-typed. */
function statusFor(startAt, cancelled) {
  if (cancelled) return "cancelled";
  return daysFromAsOf(startAt) > 0 ? "confirmed" : "completed";
}

/** One booking: a client holding one ServiceOffer slot with its practitioner.
 *  The price is the OFFER's price by construction. */
function booking(seq, serviceOfferId, clientName, clientPhone, startAt, extra = {}) {
  const svc = serviceOffers.find((s) => s.id === serviceOfferId);
  const endAt = new Date(Date.parse(startAt) + svc.minutes * 60000).toISOString().replace(".000Z", "Z");
  return {
    $type: "Booking",
    id: `bkg_${String(seq).padStart(2, "0")}`,
    serviceOfferId,
    service: svc.name,
    category: svc.category,
    practitionerId: svc.practitionerId,
    practitioner: svc.practitioner,
    client: `${clientName} (fictional)`,
    clientPhone, // NANP fictional range: NPA-555-01XX
    startAt,
    endAt,
    priceUsd: svc.priceUsd, // = the offer price, by construction
    status: statusFor(startAt, extra.cancelled),
    asOf: AS_OF,
    channel: extra.channel ?? "front-desk",
    ...(extra.note && { note: extra.note }),
    example: true,
    exampleNote: EXAMPLE_NOTE,
  };
}

/** The booking corpus — a full salon working set: completed appointments
 *  (each settled by exactly one sale record), upcoming confirmed slots, a
 *  cancellation, and one agent-channel booking (the row's native B2A2C
 *  transaction shape, labeled like everything else). */
export const bookings = [
  booking(1, "svc_01", "Tansy Ellowick", "+15125550121", "2026-08-20T15:00:00Z"),
  booking(2, "svc_03", "Rowan Hazelmarsh", "+15125550135", "2026-08-21T17:30:00Z"),
  booking(3, "svc_05", "Petra Lindenquist", "+15125550148", "2026-08-22T19:00:00Z", {
    channel: "agent",
    note: "booked by the client's scheduling agent on her behalf — the cell's native B2A2C transaction shape",
  }),
  booking(4, "svc_02", "Isolde Bramblewyn", "+15125550162", "2026-08-27T14:00:00Z"),
  booking(5, "svc_06", "Corin Ashenfield", "+15125550177", "2026-08-29T16:00:00Z", {
    channel: "agent",
    note: "requested via requestBooking — confirmed by the front desk",
  }),
  booking(6, "svc_04", "Lyra Dunmorrow", "+15125550183", "2026-08-25T13:00:00Z", {
    cancelled: true,
    note: "client cancelled 48h ahead — no charge, slot released",
  }),
];

const round2 = (n) => Math.round(n * 100) / 100;
const TAX_RATE = 0.0825; // the sandbox tenant's example sales-tax rate

/** POS sale records — one per COMPLETED booking, total derived from the
 *  booking's (= offer's) price plus tax and tip, by construction. */
export const saleRecords = bookings
  .filter((b) => b.status === "completed")
  .map((b, i) => {
    const tipUsd = round2(b.priceUsd * 0.2);
    const taxUsd = round2(b.priceUsd * TAX_RATE);
    return {
      $type: "SaleRecord",
      id: `sale_${String(i + 1).padStart(2, "0")}`,
      bookingId: b.id,
      serviceOfferId: b.serviceOfferId,
      practitionerId: b.practitionerId,
      lines: [{ item: b.service, amountUsd: b.priceUsd }],
      subtotalUsd: b.priceUsd,
      taxUsd,
      tipUsd,
      totalUsd: round2(b.priceUsd + taxUsd + tipUsd),
      settledAt: b.endAt,
      tender: "card (example)",
      example: true,
      exampleNote: EXAMPLE_NOTE,
    };
  });

/** The POS day-book summary DERIVES from the sale records — the booking ply
 *  and the POS ply tie by construction. */
export const posSummary = {
  $type: "PosSummary",
  id: "sale_summary_2026-08",
  period: "2026-08 (to " + AS_OF + ")",
  tenantId: salon.id,
  tenant: salon.name,
  sales: saleRecords.length,
  subtotalUsd: round2(saleRecords.reduce((s, x) => s + x.subtotalUsd, 0)),
  taxUsd: round2(saleRecords.reduce((s, x) => s + x.taxUsd, 0)),
  tipUsd: round2(saleRecords.reduce((s, x) => s + x.tipUsd, 0)),
  totalUsd: round2(saleRecords.reduce((s, x) => s + x.totalUsd, 0)),
  example: true,
  exampleNote: EXAMPLE_NOTE,
};

export function getBooking(id) {
  return bookings.find((x) => x.id === id);
}

export function getServiceOffer(id) {
  return serviceOffers.find((x) => x.id === id);
}

export function getSaleRecord(id) {
  if (id === posSummary.id) return posSummary;
  return saleRecords.find((x) => x.id === id);
}
