/**
 * worker.js — apis.salon, wave zero (register row personal-care, NAICS 812,
 * 8121 core; the row's ruled primary name).
 *
 * One substrate, two plies from ONE manifest (template spec §3): the data
 * face (/bookings, /service-offers, /sale-records, /establishment-licenses —
 * typed records from the row's schemas, the EstablishmentLicense corpus REAL
 * and provenance-labeled) and the headless face (the same collections as the
 * salon booking/POS system door at the register's — UNVERIFIED — scheduler/
 * booking + POS coordinate, plus the per-outcome booking verb). There is no
 * second API. The MCP door (/mcp) serves the same operations from the same
 * definitions.
 *
 * The AXP quartet + branching collection + conneg home are generated by the
 * vendored axp-faces@0.3.0 (PINS.json digest) — never hand-rolled; the four
 * axp-ext-rates-g2 fields (rates[], g2, links.verify, operationId) are
 * emitted NATIVELY by the generator from the manifest — no bridge layer
 * exists in this property. This file only composes and adds the extra live
 * doors the manifest declares.
 */

import { ok, empty, envelopeResponse, offer, createAxpRoutes } from "./axp/index.js";
import { manifest, icpDoc } from "./manifest.js";
import { mcpHandler } from "./mcp.js";
import { serviceOffers, saleRecords, posSummary, getBooking, getServiceOffer, getSaleRecord, EXAMPLE_NOTE } from "./seed.js";
import { establishmentLicenses, LICENSE_PROVENANCE, getEstablishmentLicense } from "./seed-licenses.js";
import { verifyRoutes } from "./verify.js";
import { emitMeter, emitReceipt, emitSignal } from "./seams.js";

const JSON_CT = { "content-type": "application/json; charset=utf-8" };

function json(obj, { status = 200, head = false } = {}) {
  return new Response(head ? null : JSON.stringify(obj, null, 2), { status, headers: JSON_CT });
}

const generatorRoutes = createAxpRoutes(manifest);

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const head = request.method === "HEAD";

    // ── the MCP door (same operations, second transport) ─────────────────────
    const mcpHit = await mcpHandler(request, env);
    if (mcpHit !== undefined) return mcpHit;

    // ── the machine face — the vendored generator, native extension fields ───
    const hit = await generatorRoutes(request, env);
    if (hit !== undefined) {
      if (path === manifest.collection.path) emitMeter(env, { operation: "listBookings" });
      if (path === "/" || path === "/index.html") emitSignal(env, request, { surface: "home" });
      return hit;
    }

    // ── extra live doors (every one declared in the manifest routes) ─────────
    if (request.method === "GET" || head) {
      const bkgMatch = path.match(/^\/bookings\/([A-Za-z0-9_.-]+)$/);
      if (bkgMatch) {
        emitMeter(env, { operation: "getBooking" });
        const booking = getBooking(bkgMatch[1]);
        if (!booking)
          return json(empty(`no booking '${bkgMatch[1]}' is visible to this caller`, { memberName: "bookings" }), { status: 404, head });
        return json({ type: "OK", booking }, { head });
      }

      if (path === "/service-offers") {
        emitMeter(env, { operation: "listServiceOffers" });
        const category = url.searchParams.get("category");
        const practitionerId = url.searchParams.get("practitionerId");
        const rows = serviceOffers
          .filter((s) => (category ? s.category === category : true))
          .filter((s) => (practitionerId ? s.practitionerId === practitionerId : true));
        if (rows.length === 0)
          return json(empty(`no service offers match the filter — a truthful empty set, not an error`, { memberName: "serviceOffers" }), { head });
        return json(ok(rows, { memberName: "serviceOffers" }), { head });
      }

      const svcMatch = path.match(/^\/service-offers\/([A-Za-z0-9_.-]+)$/);
      if (svcMatch) {
        emitMeter(env, { operation: "getServiceOffer" });
        const serviceOffer = getServiceOffer(svcMatch[1]);
        if (!serviceOffer) return json(empty(`no service offer '${svcMatch[1]}' is on the menu`, { memberName: "serviceOffers" }), { status: 404, head });
        return json({ type: "OK", serviceOffer }, { head });
      }

      if (path === "/sale-records") {
        emitMeter(env, { operation: "listSaleRecords" });
        const practitionerId = url.searchParams.get("practitionerId");
        const rows = practitionerId ? saleRecords.filter((s) => s.practitionerId === practitionerId) : saleRecords;
        if (rows.length === 0)
          return json(empty(`no sale records match the filter — a truthful empty set, not an error`, { memberName: "saleRecords" }), { head });
        return json(ok(rows, { memberName: "saleRecords", extra: { posSummary } }), { head });
      }

      const saleMatch = path.match(/^\/sale-records\/([A-Za-z0-9_.-]+)$/);
      if (saleMatch) {
        emitMeter(env, { operation: "getSaleRecord" });
        const saleRecord = getSaleRecord(saleMatch[1]);
        if (!saleRecord) return json(empty(`no sale record '${saleMatch[1]}' exists in this workspace`, { memberName: "saleRecords" }), { status: 404, head });
        return json({ type: "OK", saleRecord }, { head });
      }

      if (path === "/establishment-licenses") {
        emitMeter(env, { operation: "listEstablishmentLicenses" });
        const licenseNumber = url.searchParams.get("licenseNumber");
        const q = url.searchParams.get("q");
        const rows = establishmentLicenses
          .filter((r) => (licenseNumber ? r.licenseNumber === licenseNumber : true))
          .filter((r) => (q ? `${r.businessName} ${r.cityStateZip}`.toLowerCase().includes(q.toLowerCase()) : true));
        if (rows.length === 0)
          return json(empty(`no establishment licenses match the filter — a truthful empty set, not an error`, { memberName: "establishmentLicenses" }), { head });
        return json(ok(rows, { memberName: "establishmentLicenses", extra: { provenance: LICENSE_PROVENANCE } }), { head });
      }

      const licMatch = path.match(/^\/establishment-licenses\/([A-Za-z0-9_.-]+)$/);
      if (licMatch) {
        emitMeter(env, { operation: "getEstablishmentLicense" });
        const establishmentLicense = getEstablishmentLicense(licMatch[1]);
        if (!establishmentLicense)
          return json(empty(`no establishment license '${licMatch[1]}' is in the ingested corpus — see /establishment-licenses for the corpus and its provenance`, { memberName: "establishmentLicenses" }), { status: 404, head });
        return json({ type: "OK", establishmentLicense, provenance: LICENSE_PROVENANCE }, { head });
      }

      if (path === "/icp.json") {
        // the G2 document the card's g2 member mirrors (links.icp / icpUrl)
        return json(icpDoc, { head });
      }

      if (path === "/healthz") return json(ok([{ status: "ok", sandbox: "anon", note: EXAMPLE_NOTE }]), { head });

      const v = await verifyRoutes(request, url);
      if (v !== undefined) return v;
    }

    // ── the per-outcome booking door: a typed 402 OFFER; wave-zero labeled stub ─
    if (path === "/bookings" && request.method === "POST") {
      emitMeter(env, { operation: "requestBooking", shape: "paid-402" });
      emitReceipt(env, { operation: "requestBooking", offerId: "confirmed-booking-outcome" });
      return envelopeResponse(
        offer({
          ...manifest.pricing.offers[0],
          message:
            "Requesting a confirmed booking is the payable outcome door. Wave zero is test-mode: this 402 " +
            "is a labeled stub — no billing occurs. The alternatives list only mounted rungs: the free " +
            "keyless sandbox floor, or the pay rung (stub).",
        }),
        { status: 402 },
      );
    }

    return envelopeResponse(
      empty(`nothing is served at ${request.method} ${path} — the contract at /openapi.json lists every live door`),
      { status: 404 },
    );
  },
};
