/**
 * worker.ts — api.careers, wave zero: both plies from the one definition.
 *
 *   data face      GET  /placements /candidates /job-orders /occupations (+/{id})
 *   headless face  POST /placements /candidates /job-orders  — the ATS
 *                  system-of-record doors on the SAME collections, same
 *                  envelopes, same rate-card rows (there is no second API)
 *   quartet        generated by the vendored axp-faces generator from ONE
 *                  defineSiteManifest() (./manifest.ts) — never hand-rolled
 *   MCP            POST /mcp — JSON-RPC tools/list + tools/call over the SAME
 *                  operation registry the REST doors use (one definition)
 *
 * Anon sandbox is the universal floor: every door above answers keyless.
 * POST doors auto-mint an ephemeral workspace (disclosed retention). Seams
 * (metering / money events / signup-traffic) are emitted as structured
 * events, tagged per spec §6.4 — seams only, no billing, no account UI.
 */

// @ts-ignore — vendored byte-identical JS (PINS.json digest-checked); never edited here
import { createAxpRoutes, envelopeResponse, ok, empty, blocked, collectionDecision } from './axp/index.js'
import { manifest, ORIGIN } from './manifest.ts'
import { staffingTalent, type OperationDef } from './substrate.ts'
import { apiCareersProjection } from './projection.ts'
import { occupations, candidates as seedCandidates, jobOrders as seedJobOrders, placements as seedPlacements, RETENTION_NOTE } from './seed.ts'

// ─── seams (§7.4: emitted, never rendered as account UI) ────────────────────

export interface SeamEvent {
  seam: 'meter' | 'money-event' | 'receipt' | 'signup' | 'traffic'
  substrate: string
  projection: string
  motion: string
  operation?: string
  shape: string
  pattern: string
  identityClass?: string
  referral?: string
  stub?: boolean
  ts: string
  [k: string]: unknown
}

/** In-memory seam buffer — the wave-zero seam surface; a queue/analytics
 *  binding replaces the sink at extraction, the tags do not change. */
export const seams: SeamEvent[] = []

function emitSeam(event: Omit<SeamEvent, 'substrate' | 'projection' | 'motion' | 'pattern' | 'ts' | 'shape'> & { shape?: string }): void {
  const full: SeamEvent = {
    substrate: staffingTalent.substrate,
    projection: apiCareersProjection.brand,
    motion: apiCareersProjection.motion,
    pattern: apiCareersProjection.experiment.pattern,
    shape: 'anon-sandbox',
    ts: new Date().toISOString(),
    ...event,
  }
  seams.push(full)
  if (seams.length > 1000) seams.shift()
  console.log(JSON.stringify(full))
}

function identityClassOf(request: Request): { identityClass: string; referral: string } {
  const dest = request.headers.get('sec-fetch-dest')
  const identityClass = dest === 'document' ? 'human-browser' : 'machine-anonymous' // id.org.ai grain not wired at wave zero
  const referral = request.headers.get('referer') || 'direct'
  return { identityClass, referral }
}

// ─── ephemeral sandbox workspaces (auto-mint, disclosed retention) ──────────

interface Workspace {
  id: string
  mintedAt: string
  candidates: Record<string, unknown>[]
  jobOrders: Record<string, unknown>[]
  placements: Record<string, unknown>[]
}

const workspaces = new Map<string, Workspace>()

function workspaceOf(request: Request, mint: boolean): { ws: Workspace | undefined; minted: boolean } {
  const header = request.headers.get('x-workspace')
  if (header && workspaces.has(header)) return { ws: workspaces.get(header), minted: false }
  if (!mint) return { ws: undefined, minted: false }
  const id = `ws_${crypto.randomUUID().slice(0, 12)}`
  const ws: Workspace = { id, mintedAt: new Date().toISOString(), candidates: [], jobOrders: [], placements: [] }
  workspaces.set(id, ws)
  return { ws, minted: true }
}

// ─── the operation registry: one definition, REST + MCP dispatch ────────────

type OperationArgs = { id?: string; filters?: Record<string, string>; body?: Record<string, unknown>; request: Request }
type OperationResult = { status: number; body: Record<string, unknown> }

const NOT_FOUND = (what: string, id: string): OperationResult => ({
  status: 404,
  body: { type: 'EMPTY', results: [], message: `no ${what} with id ${id} — nothing was deleted; that id was never minted here` },
})

function listOf(seed: Record<string, unknown>[], wsRecords: Record<string, unknown>[] | undefined, filters: Record<string, string> | undefined, memberName: string): OperationResult {
  let recs = [...seed, ...(wsRecords || [])]
  let filtered: [string, string] | null = null
  for (const [param, value] of Object.entries(filters || {})) {
    if (param === 'status') { recs = recs.filter((r) => String(r.status) === value); filtered = [param, value] }
    if (param === 'occupation') { recs = recs.filter((r) => String(r.onetCode) === value); filtered = [param, value] }
  }
  if (recs.length === 0) {
    const [param, value] = filtered || ['status', '']
    return { status: 200, body: empty(`no records match ${param}=${value} — a truthful empty set, not an error`, { memberName }) }
  }
  return { status: 200, body: ok(recs, { memberName }) }
}

function getOf(seed: Record<string, unknown>[], wsRecords: Record<string, unknown>[] | undefined, id: string, what: string): OperationResult {
  const rec = [...seed, ...(wsRecords || [])].find((r) => String(r.id) === id)
  return rec ? { status: 200, body: ok([rec]) } : NOT_FOUND(what, id)
}

function createOf(
  args: OperationArgs,
  required: string[],
  allowed: string[],
  idPrefix: string,
  store: (ws: Workspace) => Record<string, unknown>[],
): OperationResult {
  const body = args.body || {}
  const missing = required.filter((k) => body[k] === undefined || body[k] === '')
  if (missing.length > 0) {
    return { status: 400, body: blocked(`required members missing: ${missing.join(', ')} — the door is fine, the request body is incomplete`) }
  }
  const { ws, minted } = workspaceOf(args.request, true)
  if (minted) {
    const { identityClass, referral } = identityClassOf(args.request)
    emitSeam({ seam: 'signup', identityClass, referral, workspace: ws!.id })
  }
  const picked = Object.fromEntries(Object.entries(body).filter(([k]) => allowed.includes(k)))
  const record = {
    id: `${idPrefix}_${crypto.randomUUID().slice(0, 8)}`,
    example: true as const,
    label: `sandbox-minted example record — ${RETENTION_NOTE}`,
    workspace: ws!.id,
    ...picked,
  }
  store(ws!).push(record)
  return { status: 201, body: ok([record], { extra: { workspace: ws!.id, retention: RETENTION_NOTE } }) }
}

export function executeOperation(op: OperationDef, args: OperationArgs): OperationResult {
  const wsHeader = args.request.headers.get('x-workspace')
  const ws = wsHeader ? workspaces.get(wsHeader) : undefined
  switch (op.id) {
    case 'listPlacements': {
      // workspace-merged view; the keyless (no-workspace) path is served by the
      // generator from the SAME manifest rows — one definition, one collection
      const merged = { ...manifest, collection: { ...manifest.collection, records: [...manifest.collection.records, ...(ws?.placements || [])] } }
      const params = new URLSearchParams(Object.entries(args.filters || {}))
      const d = collectionDecision(merged, params)
      return { status: d.status, body: d.body }
    }
    case 'getPlacement': return getOf(seedPlacements as unknown as Record<string, unknown>[], ws?.placements, args.id!, 'placement')
    case 'createPlacement': return createOf(args, ['candidateId', 'jobOrderId', 'onetCode'], ['candidateId', 'jobOrderId', 'onetCode', 'startDate', 'feeModel'], 'plc_ws', (w) => w.placements)
    case 'listCandidates': return listOf(seedCandidates as unknown as Record<string, unknown>[], ws?.candidates, args.filters, 'candidates')
    case 'getCandidate': return getOf(seedCandidates as unknown as Record<string, unknown>[], ws?.candidates, args.id!, 'candidate')
    case 'createCandidate': return createOf(args, ['name', 'onetCode'], ['name', 'onetCode', 'skills', 'metro'], 'cand_ws', (w) => w.candidates)
    case 'listJobOrders': return listOf(seedJobOrders as unknown as Record<string, unknown>[], ws?.jobOrders, args.filters, 'jobOrders')
    case 'getJobOrder': return getOf(seedJobOrders as unknown as Record<string, unknown>[], ws?.jobOrders, args.id!, 'jobOrder')
    case 'createJobOrder': return createOf(args, ['client', 'title', 'onetCode'], ['client', 'title', 'onetCode', 'billRateUsdHour'], 'job_ws', (w) => w.jobOrders)
    case 'listOccupations': return { status: 200, body: ok(occupations, { memberName: 'occupations' }) }
    case 'getOccupation': return getOf(occupations as unknown as Record<string, unknown>[], undefined, args.id!, 'occupation')
    default: return { status: 404, body: { type: 'EMPTY', results: [], message: `operation ${op.id} is not served` } }
  }
}

const opById = new Map(staffingTalent.operations.map((op) => [op.id, op]))

// ─── the G2 / icp document (stake #6: the row's coordinates, on the wire) ───

export const icpDocument = {
  $context: 'https://schema.org.ai',
  property: 'api.careers',
  register: {
    row: 'staffing-talent',
    kind: 'vertical',
    naics: '5613',
    sharedWith: 'fn-hr-talent (one cell, two register addresses — the vertical row leads)',
    grain: 'placement (90-day-validatable outcome)',
  },
  icp: apiCareersProjection.icp,
  personas: apiCareersProjection.personas,
  motion: apiCareersProjection.motion,
  agent_classes: [
    { id: 'reader-agent', description: 'keyless reads: the quartet, /placements, /candidates, /job-orders, /occupations, /verify — no key, no account' },
    { id: 'sandbox-transactor', description: 'mints an ephemeral workspace via any POST door and exercises the ATS system-of-record contract against labeled synthetic state' },
  ],
  ladder: [
    { rung: 0, id: 'anonymous', description: `keyless anon sandbox — ${RETENTION_NOTE}` },
  ],
} as const

// ─── /verify — the published-suite export ───────────────────────────────────

export const verifyDocument = {
  $context: 'https://schema.org.ai',
  property: 'api.careers',
  suites: [
    {
      id: 'axp-conformance',
      runner: 'vitest',
      command: 'pnpm --dir examples/api.careers test',
      spec: 'apis-ax-axp@2.6.0',
      digest: 'sha256:a9a1197c439d708b4db54f606f07c9a2d019c7f2989fbcd9b599de2fcc028e0d',
      description: 'the digest-pinned AXP conformance gate (fail-closed) — the same requirement implementations the hosted verifier at api.qa runs',
    },
    {
      id: 'property-suite',
      runner: 'vitest',
      command: 'pnpm --dir examples/api.careers test',
      description: 'property checks: seed labeling and fixture law, every operation exercised, rate-card rows ⊆ operation ids, 402 stub labeling, seam tags',
    },
  ],
  note: 'interfaces.testSuite is not declared on the card until this document is digest-pinned; these suites run from the repository today.',
} as const

// ─── MCP (JSON-RPC 2.0 — tools/list + tools/call over the one registry) ─────

async function mcpResponse(request: Request): Promise<Response> {
  let rpc: { jsonrpc?: string; id?: unknown; method?: string; params?: { name?: string; arguments?: Record<string, unknown> } }
  try {
    rpc = await request.json()
  } catch {
    return Response.json({ jsonrpc: '2.0', id: null, error: { code: -32700, message: 'parse error — body must be JSON-RPC 2.0' } }, { status: 400 })
  }
  const reply = (result: unknown) => Response.json({ jsonrpc: '2.0', id: rpc.id ?? null, result })
  const error = (code: number, message: string, status = 400) =>
    Response.json({ jsonrpc: '2.0', id: rpc.id ?? null, error: { code, message } }, { status })

  switch (rpc.method) {
    case 'initialize':
      return reply({ protocolVersion: '2025-06-18', serverInfo: { name: 'api.careers', version: manifest.version }, capabilities: { tools: {} } })
    case 'tools/list':
      return reply({
        tools: staffingTalent.operations.map((op) => ({
          name: op.id,
          description: op.summary,
          inputSchema: {
            type: 'object',
            properties: {
              ...(op.verb === 'get' && { id: { type: 'string' } }),
              ...(op.verb === 'list' && { status: { type: 'string' }, occupation: { type: 'string' } }),
              ...(op.verb === 'create' && { record: { type: 'object' } }),
            },
            ...(op.verb === 'get' && { required: ['id'] }),
          },
        })),
      })
    case 'tools/call': {
      const name = rpc.params?.name
      const op = name ? opById.get(name) : undefined
      if (!op) return error(-32602, `unknown tool ${JSON.stringify(name)} — tools/list names the served set`)
      const a = rpc.params?.arguments || {}
      const result = executeOperation(op, {
        id: typeof a.id === 'string' ? a.id : undefined,
        filters: Object.fromEntries(Object.entries(a).filter(([k, v]) => (k === 'status' || k === 'occupation') && typeof v === 'string')) as Record<string, string>,
        body: (a.record as Record<string, unknown>) || (a as Record<string, unknown>),
        request,
      })
      emitSeam({ seam: 'meter', operation: op.id, transport: 'mcp' })
      return reply({ content: [{ type: 'text', text: JSON.stringify(result.body) }], isError: result.status >= 400 })
    }
    default:
      return error(-32601, `method ${JSON.stringify(rpc.method)} is not served — this door answers initialize, tools/list, tools/call`)
  }
}

// ─── the fetch pipeline ──────────────────────────────────────────────────────

const axp = createAxpRoutes(manifest)

const JSON_CT = { 'content-type': 'application/json; charset=utf-8' }

/** One REST door: scope law, body parse, registry dispatch, meter seam. */
async function serveOperation(op: OperationDef, request: Request, url: URL): Promise<Response> {
  // reserved scopes answer BLOCKED on every collection, not only the branching one
  const scope = url.searchParams.get('scope')
  if (scope !== null && ['admin', 'internal'].includes(scope)) {
    return envelopeResponse(blocked(`scope '${scope}' is reserved to the platform — not permitted for your agent class`))
  }
  const id = op.verb === 'get' ? url.pathname.split('/').pop() : undefined
  let body: Record<string, unknown> | undefined
  if (request.method === 'POST') {
    try {
      body = await request.json()
    } catch {
      return envelopeResponse(blocked('the request body must be JSON'), { status: 400 })
    }
  }
  const result = executeOperation(op, { id, filters: Object.fromEntries(url.searchParams), body, request })
  emitSeam({ seam: 'meter', operation: op.id })
  return new Response(JSON.stringify(result.body), { status: result.status, headers: JSON_CT })
}

function meterFor(path: string, method: string): string | undefined {
  if (method === 'GET') {
    if (path === '/placements') return 'listPlacements'
    if (/^\/placements\/[^/]+$/.test(path)) return 'getPlacement'
    if (path === '/candidates') return 'listCandidates'
    if (/^\/candidates\/[^/]+$/.test(path)) return 'getCandidate'
    if (path === '/job-orders') return 'listJobOrders'
    if (/^\/job-orders\/[^/]+$/.test(path)) return 'getJobOrder'
    if (path === '/occupations') return 'listOccupations'
    if (/^\/occupations\/[^/]+$/.test(path)) return 'getOccupation'
  }
  if (method === 'POST') {
    if (path === '/placements') return 'createPlacement'
    if (path === '/candidates') return 'createCandidate'
    if (path === '/job-orders') return 'createJobOrder'
  }
  return undefined
}

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url)
    const path = url.pathname
    const method = request.method

    // MCP door (declared on the card — presence-when-true, and it answers)
    if (path === '/mcp' && method === 'POST') return mcpResponse(request)

    // headless-ply POST doors — BEFORE the generator, which owns the
    // collection path for GET/HEAD and would answer 405 to a POST it never
    // serves (the POST door is ours, on the same collection — one definition)
    if (method === 'POST') {
      const operation = meterFor(path, 'POST')
      if (operation) return serveOperation(opById.get(operation)!, request, url)
    }

    // workspace-merged collection read (same manifest rows; the keyless path
    // stays with the generator so probe behavior is the generator's, verbatim)
    if (path === '/placements' && method === 'GET' && request.headers.get('x-workspace')) {
      const op = opById.get('listPlacements')!
      const result = executeOperation(op, { filters: Object.fromEntries(url.searchParams), request })
      emitSeam({ seam: 'meter', operation: op.id })
      return new Response(JSON.stringify(result.body), { status: result.status, headers: JSON_CT })
    }

    // the generated quartet + collection + offer + family + home
    const hit = await axp(request)
    if (hit !== undefined) {
      const metered = meterFor(path, method)
      if (metered) emitSeam({ seam: 'meter', operation: metered })
      if (path === manifest.pricing.offerPath || hit.status === 402) {
        // §7.4 money-event seam — a labeled stub: an offer boundary was served;
        // no settlement occurs on this deployment
        emitSeam({ seam: 'money-event', kind: 'offer-served', stub: true, operation: metered })
      }
      if (path === '/') {
        const { identityClass, referral } = identityClassOf(request)
        emitSeam({ seam: 'traffic', identityClass, referral })
      }
      return hit
    }

    // machine-face extras
    if (path === '/icp.json' && (method === 'GET' || method === 'HEAD')) {
      return new Response(method === 'HEAD' ? null : JSON.stringify(icpDocument, null, 2), { status: 200, headers: JSON_CT })
    }
    if (path === '/verify' && (method === 'GET' || method === 'HEAD')) {
      return new Response(method === 'HEAD' ? null : JSON.stringify(verifyDocument, null, 2), { status: 200, headers: JSON_CT })
    }

    // the two plies — remaining REST doors over the one operation registry
    const operation = meterFor(path, method)
    if (operation) return serveOperation(opById.get(operation)!, request, url)

    return envelopeResponse(
      { type: 'EMPTY', results: [], message: `no route at ${path} — nothing here has been deleted; the route was never written. The card at ${ORIGIN}/.well-known/agents.json names every door.` },
      { status: 404 },
    )
  },
}
