/**
 * seed.js — the §5.2 sandbox seed corpus for the `nonprofits-civic` substrate
 * (register row: NAICS 813). SYNTHETIC, ALWAYS LABELED: the row's source
 * route is not ruled ("None ruled" — the IRS 990 / EO BMF public-record
 * ingest is a candidate marked [UNVERIFIED as applied]), so wave zero seeds
 * the mechanical §5.2 synthetic corpus and performs NO real-world ingest.
 * Every record carries `"example": true` plus a worded label; every EIN is
 * the synthetic 00-prefix pattern (no real EIN begins 00); every
 * organization, person, and place name is fictional (no-real-name collision
 * check run at authoring). The sandbox is the live product over simulated
 * data — never a faked demo (live-demo ruling, RATIFIED 2026-08-02).
 *
 * Deliberate breadth: the nine organizations span NAICS 8131 (religious),
 * 8132 (grantmaking/giving), and 8134 (civic/social) — including a civic
 * league, an HOA, and a veterans post — because the row's own curation flag
 * says 'charity' does not cover all of 813. The seed makes that scope
 * question visible instead of hiding it.
 *
 * Reseeding is a build step: this module is versioned with the manifest.
 */

const EXAMPLE_LABEL =
  'example data — synthetic record on the apis.charity sandbox (fictional organizations and people, synthetic 00-prefix EINs); not derived from IRS 990/EO BMF or any real filing'

const ex = (rec) => ({ ...rec, example: true, label: EXAMPLE_LABEL })

/** Organization — the org-level typed record (schema.org.ai/Organization).
 *  Filters served on the collection: ?subsection= and ?ntee=. */
export const organizations = [
  ex({
    $type: 'Organization',
    id: 'harborlight-food-bank',
    name: 'Harborlight Food Bank (fictional)',
    ein: '00-0000101',
    subsection: '501(c)(3)',
    ntee: 'K31',
    naics: '8132',
    city: 'Meridian Falls',
    state: 'OH',
    rulingYear: 2009,
    fiscalYearEnd: '06-30',
    revenue: 1840000,
    assets: 962000,
    employees: 14,
    volunteers: 210,
    mission: 'Food security for the three-county Meridian Falls region.',
  }),
  ex({
    $type: 'Organization',
    id: 'cedar-ridge-community-church',
    name: 'Cedar Ridge Community Church (fictional)',
    ein: '00-0000102',
    subsection: '501(c)(3)',
    ntee: 'X20',
    naics: '8131',
    city: 'Cedar Ridge',
    state: 'TN',
    rulingYear: 1987,
    fiscalYearEnd: '12-31',
    revenue: 640000,
    assets: 2210000,
    employees: 6,
    volunteers: 85,
    mission: 'Congregational worship and neighborhood care in Cedar Ridge.',
  }),
  ex({
    $type: 'Organization',
    id: 'riverbend-civic-league',
    name: 'Riverbend Civic League (fictional)',
    ein: '00-0000103',
    subsection: '501(c)(4)',
    ntee: 'W24',
    naics: '8134',
    city: 'Riverbend',
    state: 'IA',
    rulingYear: 1994,
    fiscalYearEnd: '12-31',
    revenue: 88000,
    assets: 41000,
    employees: 0,
    volunteers: 40,
    mission: 'Civic improvement and public-forum programming for Riverbend.',
  }),
  ex({
    $type: 'Organization',
    id: 'oakmont-commons-association',
    name: 'Oakmont Commons Homeowners Association (fictional)',
    ein: '00-0000104',
    subsection: '501(c)(4)',
    ntee: 'W99',
    naics: '8134',
    city: 'Oakmont',
    state: 'CO',
    rulingYear: 2003,
    fiscalYearEnd: '12-31',
    revenue: 312000,
    assets: 505000,
    employees: 1,
    volunteers: 12,
    mission: 'Common-area stewardship for the 240-home Oakmont Commons.',
  }),
  ex({
    $type: 'Organization',
    id: 'bluff-city-grantmakers-fund',
    name: 'Bluff City Grantmakers Fund (fictional)',
    ein: '00-0000105',
    subsection: '501(c)(3) private foundation',
    ntee: 'T20',
    naics: '8132',
    city: 'Bluff City',
    state: 'MO',
    rulingYear: 1978,
    fiscalYearEnd: '12-31',
    revenue: 2950000,
    assets: 46800000,
    employees: 4,
    volunteers: 0,
    mission: 'Grantmaking for human services and the arts across Bluff City.',
  }),
  ex({
    $type: 'Organization',
    id: 'lakeshore-service-circle',
    name: 'Lakeshore Service Circle (fictional)',
    ein: '00-0000106',
    subsection: '501(c)(4)',
    ntee: 'S80',
    naics: '8134',
    city: 'Lakeshore',
    state: 'MI',
    rulingYear: 1969,
    fiscalYearEnd: '06-30',
    revenue: 54000,
    assets: 23000,
    employees: 0,
    volunteers: 65,
    mission: 'Member-run community service projects around Lakeshore.',
  }),
  ex({
    $type: 'Organization',
    id: 'northgate-animal-rescue',
    name: 'Northgate Animal Rescue (fictional)',
    ein: '00-0000107',
    subsection: '501(c)(3)',
    ntee: 'D20',
    naics: '8132',
    city: 'Northgate',
    state: 'WA',
    rulingYear: 2015,
    fiscalYearEnd: '12-31',
    revenue: 410000,
    assets: 188000,
    employees: 5,
    volunteers: 120,
    mission: 'Shelter, foster, and adoption services for companion animals.',
  }),
  ex({
    $type: 'Organization',
    id: 'summit-veterans-post-88',
    name: 'Summit Veterans Post 88 (fictional)',
    ein: '00-0000108',
    subsection: '501(c)(19)',
    ntee: 'W30',
    naics: '8134',
    city: 'Summit',
    state: 'PA',
    rulingYear: 1952,
    fiscalYearEnd: '12-31',
    revenue: 97000,
    assets: 350000,
    employees: 2,
    volunteers: 30,
    mission: 'Member services and community programs for area veterans.',
  }),
  ex({
    $type: 'Organization',
    id: 'willow-park-arts-alliance',
    name: 'Willow Park Arts Alliance (fictional)',
    ein: '00-0000109',
    subsection: '501(c)(3)',
    ntee: 'A20',
    naics: '8132',
    city: 'Willow Park',
    state: 'NC',
    rulingYear: 2011,
    fiscalYearEnd: '09-30',
    revenue: 265000,
    assets: 90000,
    employees: 3,
    volunteers: 55,
    mission: 'Public arts programming and small-grant regranting in Willow Park.',
  }),
]

/** Donor — the donor-CRM grain (fictional people only, fixture law). */
export const donors = [
  ex({
    $type: 'Person',
    id: 'donor-avery-quill',
    name: 'Avery Quill (fictional)',
    donorType: 'individual',
    since: '2019-03-11',
    lifetimeGiving: 14250,
    recurring: true,
  }),
  ex({
    $type: 'Person',
    id: 'donor-rowan-hale',
    name: 'Rowan Hale (fictional)',
    donorType: 'individual',
    since: '2021-10-02',
    lifetimeGiving: 3600,
    recurring: false,
  }),
  ex({
    $type: 'Person',
    id: 'donor-jules-marsh',
    name: 'Jules Marsh (fictional)',
    donorType: 'individual',
    since: '2016-06-20',
    lifetimeGiving: 41800,
    recurring: true,
  }),
  ex({
    $type: 'Organization',
    id: 'donor-meridian-falls-hardware',
    name: 'Meridian Falls Hardware Co. (fictional)',
    donorType: 'corporate',
    since: '2020-01-15',
    lifetimeGiving: 22000,
    recurring: false,
  }),
]

/** Donation — a full giving cycle on the donor-CRM System: pledge →
 *  received → receipted; recurring, in-kind, and restricted gifts all
 *  present so the noun has realistic depth (§5.2 quality bar). */
export const donations = [
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0001',
    org: 'harborlight-food-bank',
    donor: 'donor-avery-quill',
    amount: 250,
    currency: 'USD',
    status: 'received',
    method: 'card',
    recurring: 'monthly',
    fund: 'general',
    pledgedAt: '2026-07-01',
    receivedAt: '2026-07-01',
    receiptId: 'rcpt-2026-0001',
    acknowledgedAt: '2026-07-02',
  }),
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0002',
    org: 'harborlight-food-bank',
    donor: 'donor-jules-marsh',
    amount: 10000,
    currency: 'USD',
    status: 'received',
    method: 'check',
    recurring: null,
    fund: 'building',
    restriction: 'restricted — cold-storage expansion',
    pledgedAt: '2026-05-14',
    receivedAt: '2026-06-03',
    receiptId: 'rcpt-2026-0002',
    acknowledgedAt: '2026-06-04',
  }),
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0003',
    org: 'harborlight-food-bank',
    donor: 'donor-meridian-falls-hardware',
    amount: 4800,
    currency: 'USD',
    status: 'received',
    method: 'in-kind',
    inKindDescription: 'shelving and pallet jacks (fair value)',
    fund: 'general',
    receivedAt: '2026-04-22',
    receiptId: 'rcpt-2026-0003',
    acknowledgedAt: '2026-04-23',
  }),
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0004',
    org: 'harborlight-food-bank',
    donor: 'donor-rowan-hale',
    amount: 600,
    currency: 'USD',
    status: 'pledged',
    method: 'card',
    fund: 'general',
    pledgedAt: '2026-08-15',
  }),
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0005',
    org: 'northgate-animal-rescue',
    donor: 'donor-avery-quill',
    amount: 120,
    currency: 'USD',
    status: 'received',
    method: 'card',
    recurring: 'monthly',
    fund: 'general',
    receivedAt: '2026-08-01',
    receiptId: 'rcpt-2026-0005',
    acknowledgedAt: '2026-08-01',
  }),
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0006',
    org: 'willow-park-arts-alliance',
    donor: 'donor-jules-marsh',
    amount: 1500,
    currency: 'USD',
    status: 'received',
    method: 'ach',
    fund: 'season-2026',
    receivedAt: '2026-03-10',
    receiptId: 'rcpt-2026-0006',
    acknowledgedAt: '2026-03-11',
  }),
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0007',
    org: 'cedar-ridge-community-church',
    donor: 'donor-rowan-hale',
    amount: 200,
    currency: 'USD',
    status: 'received',
    method: 'cash',
    fund: 'benevolence',
    receivedAt: '2026-08-10',
    receiptId: 'rcpt-2026-0007',
    acknowledgedAt: '2026-08-10',
  }),
  ex({
    $type: 'DonateAction',
    id: 'don-2026-0008',
    org: 'summit-veterans-post-88',
    donor: 'donor-meridian-falls-hardware',
    amount: 750,
    currency: 'USD',
    status: 'refunded',
    method: 'card',
    fund: 'general',
    receivedAt: '2026-02-18',
    refundedAt: '2026-02-25',
    refundReason: 'duplicate charge — donor gave twice in error',
  }),
]

/** Grant — the grant-management grain: application → award →
 *  disbursement, with a pending and a declined application so the empty
 *  and negative branches are honest. */
export const grants = [
  ex({
    $type: 'Grant',
    id: 'grant-2026-011',
    funder: 'bluff-city-grantmakers-fund',
    grantee: 'harborlight-food-bank',
    program: 'human-services',
    amount: 75000,
    currency: 'USD',
    status: 'paid',
    appliedAt: '2025-11-01',
    awardedAt: '2026-01-15',
    period: { start: '2026-02-01', end: '2027-01-31' },
    disbursements: [
      { at: '2026-02-01', amount: 37500 },
      { at: '2026-08-01', amount: 37500 },
    ],
    report: { due: '2027-02-28', received: null },
  }),
  ex({
    $type: 'Grant',
    id: 'grant-2026-012',
    funder: 'bluff-city-grantmakers-fund',
    grantee: 'willow-park-arts-alliance',
    program: 'arts',
    amount: 20000,
    currency: 'USD',
    status: 'awarded',
    appliedAt: '2026-03-01',
    awardedAt: '2026-06-20',
    period: { start: '2026-09-01', end: '2027-08-31' },
    disbursements: [],
    report: { due: '2027-09-30', received: null },
  }),
  ex({
    $type: 'Grant',
    id: 'grant-2026-013',
    funder: 'bluff-city-grantmakers-fund',
    grantee: 'northgate-animal-rescue',
    program: 'human-services',
    amount: 15000,
    currency: 'USD',
    status: 'applied',
    appliedAt: '2026-07-30',
  }),
  ex({
    $type: 'Grant',
    id: 'grant-2026-014',
    funder: 'bluff-city-grantmakers-fund',
    grantee: 'riverbend-civic-league',
    program: 'civic',
    amount: 10000,
    currency: 'USD',
    status: 'declined',
    appliedAt: '2026-02-10',
    declinedAt: '2026-04-05',
    declineReason: 'outside the 2026 program scope (civic-infrastructure cycle opens 2027)',
  }),
  ex({
    $type: 'Grant',
    id: 'grant-2025-091',
    funder: 'bluff-city-grantmakers-fund',
    grantee: 'harborlight-food-bank',
    program: 'human-services',
    amount: 60000,
    currency: 'USD',
    status: 'closed',
    appliedAt: '2024-11-01',
    awardedAt: '2025-01-20',
    period: { start: '2025-02-01', end: '2026-01-31' },
    disbursements: [
      { at: '2025-02-01', amount: 30000 },
      { at: '2025-08-01', amount: 30000 },
    ],
    report: { due: '2026-02-28', received: '2026-02-14' },
  }),
]
