/**
 * worker.js — the fn-risk-compliance wave-zero property: one Workers-shaped
 * fetch handler serving BOTH plies from ONE definition (template spec §3):
 *
 *   data face      GET /statutes, /checks (branching collection),
 *                  /checks/{id}, /check-runs, /check-runs/{id},
 *                  /obligations, /obligations/{id}
 *   headless face  POST /checks/{id}/runs — the shared check-runner door,
 *                  system-of-record verb on the SAME collections, same
 *                  envelopes (the family's one pipeline)
 *   machine face   the AXP quartet + probes, generated by the vendored
 *                  axp-faces 0.3.0 (pinned apis-ax-axp@2.6.0, extension
 *                  axp-ext-rates-g2@0.2.0 native) — never hand-rolled
 *   MCP door       POST /mcp — the same Nouns/verbs over JSON-RPC (authless,
 *                  the anon-sandbox rung only; keyed rungs above are stubs)
 *   verify         GET /verify, /verify/suite.json — "run our tests"
 *   icp            GET /icp.json — the G2 coordinates + agent classes
 *
 * WAVE-ZERO HONESTY, stated once and enforced below:
 *   - statute/check-definition records are cited reference facts (public-law
 *     citations + estate-register rows) with the no-registry-fetch
 *     disclosure on every record; every RESULT and calendar entry is labeled
 *     synthetic example data (see ./seed.js);
 *   - runs are per-isolate and ephemeral (disclosed on every response); no
 *     run is ever attested (attested: false; the api.qa VerificationReport
 *     rail is a consumption edge — no verdict URL is fabricated);
 *   - the rate card is a stub (binding: false + statement); the 402 OFFER
 *     boundary is real and probeable, but nothing settles and nothing charges;
 *   - seams (metering / money / traffic events) are EMITTED per template §7.4
 *     — structured events tagged {substrate, projection, motion, operation,
 *     shape, pattern} — but no dashboard, billing, or account surface exists
 *     here, by design.
 */

import { createAxpRoutes } from './axp/routes.js'
import { buildCard } from './axp/card.js'
import { envelopeResponse, ok, empty } from './axp/envelope.js'
import { negotiate, serveFace, AGENT_UA_TOKENS } from './axp/conneg.js'
import { manifest, ORIGIN, g2 } from './manifest.js'
import { statutes, checkDefinitions, checkRuns, obligations } from './seed.js'
import { seamTags } from './substrate.js'

const RETENTION = 'ephemeral — per-isolate memory only; no durability at wave zero'
const ATTESTATION_RAIL =
  'api.qa VerificationReport (consumption edge; no attestation attached at wave zero — no verdict URL is fabricated)'

// ── the card: generator truth, whole (spec §4.1) ────────────────────────────
// links.verify and the top-level g2 object are NATIVE generator emissions
// (axp-faces 0.3.0 / axp-ext-rates-g2@0.2.0) — no site-side bridges anywhere.
const card = buildCard(manifest)

const axp = createAxpRoutes(manifest)

// ── per-isolate state (the auto-minted anon workspace, §5.2/#17) ────────────
const state = {
  statutes: new Map(statutes.map((s) => [s.id, structuredClone(s)])),
  checks: new Map(checkDefinitions.map((c) => [c.id, structuredClone(c)])),
  checkRuns: new Map(checkRuns.map((r) => [r.id, structuredClone(r)])),
  obligations: new Map(obligations.map((o) => [o.id, structuredClone(o)])),
  minted: 0,
}

// ── seams (template §7.4 — emitted, never rendered; no account UI here) ────
function emitSeam(env, event) {
  const line = JSON.stringify({ ...seamTags, ts: new Date().toISOString(), ...event })
  if (globalThis.__SEAM_SILENT !== true) console.log(line)
  if (env && env.SEAMS && typeof env.SEAMS.send === 'function') {
    try {
      env.SEAMS.send(JSON.parse(line))
    } catch {
      /* the seam is best-effort transport, never a request failure */
    }
  }
}

function identityClass(request) {
  // id.org.ai grain is not wired at wave zero — only the CLASS is derivable.
  const mode = request.headers.get('sec-fetch-mode')
  const dest = request.headers.get('sec-fetch-dest')
  if (mode === 'navigate' || dest === 'document') return 'human-browser'
  const ua = (request.headers.get('user-agent') || '').toLowerCase()
  if (AGENT_UA_TOKENS.some((t) => ua.includes(t))) return 'machine-agent'
  return 'machine-unattributed'
}

// ── three-faced serving for this worker's own GET addresses ────────────────
function threeFaces(title, obj) {
  const json = obj
  const md = `# ${title}\n\n\`\`\`json\n${JSON.stringify(obj, null, 2)}\n\`\`\`\n`
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const html = `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><title>${esc(title)}</title></head>\n<body><h1>${esc(title)}</h1><pre>${esc(JSON.stringify(obj, null, 2))}</pre></body></html>\n`
  return { json, md, html }
}

// ── the ICP document: the row's G2 coordinates, exposed ─────────────────────
// ONE truth: the same g2 object manifest.js puts on the card (top-level g2,
// axp-ext-rates-g2 §4) is served here at /icp.json (links.icp stays beside it).
const icpDocument = {
  $context: 'https://schema.org.ai',
  property: 'fn-risk-compliance.org.ai',
  substrate: 'fn-risk-compliance',
  g2,
  system: { system: 'ComplianceManagement', coordinates: g2.coordinates },
  agent_classes: g2.agentClasses,
}

// ── the published suite (links.verify target) ───────────────────────────────
// interfaces.testSuite is deliberately NOT declared on the card: declaring it
// arms check-capability-coverage, which the deployed verifier (autonomous-qa
// 0.3.0) does not implement — the api.lawyer reference posture. The suite
// still ships and links.verify names it: "trust us" → "run this".
const suiteDocument = {
  $type: 'VerifySuite',
  property: 'fn-risk-compliance.org.ai',
  version: '0.1.0',
  runner: 'node selfcheck.mjs (repo: examples/fn-risk-compliance — fail-closed, digest-pinned)',
  pinnedSpec: 'apis-ax-axp@2.6.0',
  pinnedSpecDigest: 'a9a1197c439d708b4db54f606f07c9a2d019c7f2989fbcd9b599de2fcc028e0d',
  tests: [
    { id: 'vendored-pins', asserts: 'every vendored axp-faces file is byte-identical to its VENDORED.json digest (source commit 523c9ef2… recorded); the PINS.json spec digest equals the ratified pin and the extension pin equals axp-ext-rates-g2@0.2.0 (903e414d…)' },
    { id: 'pinned-conformance', asserts: 'the probe ladder passes the pinned apis-ax-axp@2.6.0 spec in-process (autonomous-qa gradePinned — disclosed: describeConformance is absent from vendored axp-faces 0.3.0, so the ladder runs via the independent verifier in-process)' },
    { id: 'seed-honesty', asserts: 'reference records (statutes, check definitions) each carry citation-grade provenance and the no-registry-fetch disclosure; every run/obligation record carries example: true and a [demo] title; fictional names only; no run is attested' },
    { id: 'operations-exercised', asserts: 'every declared operation answers substantively against the seed (no ghost surfaces)' },
    { id: 'conneg-matrix', asserts: 'bare curl → JSON; Accept: text/markdown → md; browser navigation → HTML, on this worker’s own addresses' },
    { id: 'offer-ladder', asserts: 'the 402 OFFER at /offer carries the pay/work/claim alternatives, every rung labeled a stub (mounted-rungs-only)' },
    { id: 'head-mirrors-get', asserts: 'HEAD answers wherever GET answers, same status and headers' },
    { id: 'typed-405', asserts: 'non-GET on a GET-only AXP address answers a typed BLOCKED envelope with Allow' },
    {
      id: 'rates-g2-native',
      asserts:
        'the axp-ext-rates-g2@0.2.0 members are generator-native at the ruled placements: top-level rates[] in the Pricing Document keyed on declared operationIds, operationId on every OpenAPI operation, links.verify on the card, top-level g2 on the card',
    },
  ],
}

const verifyPage = {
  title: 'fn-risk-compliance.org.ai — run our tests',
  body:
    'The published verification suite for this surface. Every claim the machine face makes is checked by a runnable test, ' +
    'not an adjective: the suite document at /verify/suite.json lists each check; the runner is selfcheck.mjs beside this ' +
    'worker in its repository, fail-closed against the pinned apis-ax-axp@2.6.0 spec (digest a9a1197c…). Independent verdict: ' +
    'https://api.qa/fn-risk-compliance.org.ai.',
  suite: `${ORIGIN}/verify/suite.json`,
  conformance: 'https://api.qa/fn-risk-compliance.org.ai',
}

// ── domain views (typed envelopes; the record IS the wire truth) ────────────
const listOf = (map) => [...map.values()]

function getRecord(map, id, what) {
  const rec = map.get(id)
  if (rec === undefined) return { status: 200, body: empty(`no ${what} with id ${id} — a truthful empty result, not an error`) }
  return { status: 200, body: ok([rec]) }
}

// ── MCP (same definition, JSON-RPC transport; authless anon-sandbox rung) ──
const mcpTools = {
  listStatutes: { description: 'List the family’s statutes (public-law citation records, provenance disclosed)', input: {}, call: () => listOf(state.statutes) },
  getStatute: { description: 'Get one statute by id', input: { statuteId: 'string' }, call: (a) => state.statutes.get(String(a.statuteId)) ?? null },
  listChecks: {
    description: 'List check definitions (the family register of held per-statute .dev fronts); optional filters statuteId, front',
    input: { statuteId: 'string?', front: 'string?' },
    call: (a) => listOf(state.checks).filter((c) => (a.statuteId ? c.statuteId === a.statuteId : true) && (a.front ? c.front === a.front : true)),
  },
  getCheck: { description: 'Get one check definition by id', input: { checkId: 'string' }, call: (a) => state.checks.get(String(a.checkId)) ?? null },
  runCheck: {
    description: 'Run a check against a subject (labeled synthetic result; ephemeral; attested: false — no live registry consulted at wave zero)',
    input: { checkId: 'string', subject: 'object?' },
    call: (a) => mintRun(String(a.checkId), a.subject && typeof a.subject === 'object' ? a.subject : {}),
  },
  listCheckRuns: { description: 'List check runs (labeled demo seed + anything minted in this isolate)', input: {}, call: () => listOf(state.checkRuns) },
  getCheckRun: { description: 'Get one check run by id', input: { runId: 'string' }, call: (a) => state.checkRuns.get(String(a.runId)) ?? null },
  listObligations: { description: 'List compliance-calendar obligations (labeled demo seed)', input: {}, call: () => listOf(state.obligations) },
  getObligation: { description: 'Get one obligation by id', input: { obligationId: 'string' }, call: (a) => state.obligations.get(String(a.obligationId)) ?? null },
}

/** The shared check-runner: ONE pipeline for the whole family (family grain). */
function mintRun(checkId, subject) {
  const check = state.checks.get(checkId)
  if (!check) return null
  state.minted += 1
  const label = (v) => (typeof v === 'string' && !v.startsWith('[demo]') ? `[demo] ${v}` : v)
  const labeledSubject = Object.fromEntries(Object.entries(subject).map(([k, v]) => [k, typeof v === 'string' ? label(v) : v]))
  const rec = {
    id: `run-anon-${state.minted}`,
    $type: 'https://schema.org.ai/CheckRun',
    example: true, // everything minted in the anon sandbox is example data by definition
    title: `[demo] ${check.front} check run (anon sandbox)`,
    checkId,
    statuteId: check.statuteId,
    subject: labeledSubject,
    verdict: check.statuteId
      ? 'indeterminate — wave-zero sandbox: no live registry is consulted; this run exercises the pipeline shape only'
      : 'unbound — this front’s statute binding is [UNVERIFIED] in the register; no check logic is improvised for it',
    findings: [],
    attested: false,
    attestationRail: ATTESTATION_RAIL,
    workspace: 'anon',
    retention: RETENTION,
  }
  state.checkRuns.set(rec.id, rec)
  return rec
}

function mcpResponse(id, result) {
  return new Response(JSON.stringify({ jsonrpc: '2.0', id, result }), { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } })
}
function mcpError(id, code, message) {
  return new Response(JSON.stringify({ jsonrpc: '2.0', id, error: { code, message } }), { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } })
}

async function handleMcp(request, env) {
  let msg
  try {
    msg = await request.json()
  } catch {
    return mcpError(null, -32700, 'parse error — the /mcp door speaks JSON-RPC 2.0')
  }
  const { id = null, method, params = {} } = msg || {}
  if (method === 'initialize') {
    return mcpResponse(id, {
      protocolVersion: '2024-11-05',
      capabilities: { tools: {} },
      serverInfo: { name: 'fn-risk-compliance.org.ai', version: '0.1.0' },
    })
  }
  if (method === 'notifications/initialized') return new Response(null, { status: 202 })
  if (method === 'tools/list') {
    return mcpResponse(id, {
      tools: Object.entries(mcpTools).map(([name, t]) => ({
        name,
        description: t.description,
        inputSchema: { type: 'object', properties: Object.fromEntries(Object.entries(t.input).map(([k, v]) => [k, { type: String(v).replace('?', '') }])) },
      })),
    })
  }
  if (method === 'tools/call') {
    const tool = mcpTools[params.name]
    if (!tool) return mcpError(id, -32602, `unknown tool ${JSON.stringify(params.name)} — tools/list names every tool that exists`)
    emitSeam(env, { seam: 'meter', operation: params.name, shape: 'anon-sandbox', transport: 'mcp' })
    const result = tool.call(params.arguments || {})
    return mcpResponse(id, { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }], isError: false })
  }
  return mcpError(id, -32601, `method ${JSON.stringify(method)} is not served — this door answers initialize, tools/list, tools/call`)
}

// ── router ──────────────────────────────────────────────────────────────────
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const path = url.pathname
    const method = request.method

    emitSeam(env, {
      seam: 'traffic',
      path,
      method,
      identity: null, // id.org.ai grain not wired at wave zero — class only
      identityClass: identityClass(request),
      referral: request.headers.get('referer') || null,
    })

    // 1. the card (generator-emitted whole — links.verify and g2 are native)
    if (path === '/.well-known/agents.json' && (method === 'GET' || method === 'HEAD')) {
      return new Response(method === 'HEAD' ? null : JSON.stringify(card, null, 2), {
        status: 200,
        headers: { 'content-type': 'application/json; charset=utf-8' },
      })
    }

    // 2. the headless door BEFORE the generator (its mounted paths answer 405
    //    to non-GET; this POST is a real system-of-record door)
    const runMatch = path.match(/^\/checks\/([^/]+)\/runs$/)
    if (runMatch && method === 'POST') {
      let input
      try {
        input = await request.json()
      } catch {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the check-runner door takes a JSON body: { subject }' }, { status: 403 })
      }
      if (!input || typeof input.subject !== 'object' || input.subject === null) {
        return envelopeResponse({ type: 'BLOCKED', reason: 'subject (object) is required — { subject: { … } }' }, { status: 403 })
      }
      const checkId = decodeURIComponent(runMatch[1])
      const rec = mintRun(checkId, input.subject)
      if (rec === null) {
        return envelopeResponse(empty(`no check definition with id ${checkId} — a truthful empty result, not an error`))
      }
      emitSeam(env, { seam: 'meter', operation: 'runCheck', shape: 'anon-sandbox' })
      return envelopeResponse(ok([rec], { extra: { retention: RETENTION } }), { status: 201 })
    }

    // 3. the MCP door (authless — the anon-sandbox rung only)
    if (path === '/mcp') {
      if (method !== 'POST') {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the /mcp door speaks JSON-RPC 2.0 over POST' }, { status: 405, headers: { allow: 'POST' } })
      }
      return handleMcp(request, env)
    }

    // 4. the generated machine face (quartet, branching collection, offer, home)
    const hit = await axp(request, env)
    if (hit !== undefined) {
      if (path === manifest.collection.path && method === 'GET') {
        emitSeam(env, { seam: 'meter', operation: 'listChecks', shape: 'anon-sandbox' })
      }
      if (hit.status === 402) {
        // money seam: an OFFER was presented. Nothing settles at wave zero —
        // the event exists so the rail ledger can count the boundary.
        emitSeam(env, { seam: 'money', event: 'offer-presented', operation: path === manifest.pricing.offerPath ? 'getOffer' : 'listChecks', settlement: 'none — stub rate card' })
      }
      return hit
    }

    // 5. this worker's own GET addresses (conneg-served, three faces)
    if (method === 'GET' || method === 'HEAD') {
      const { face, cleanPath } = negotiate(request, path)

      const serve = (title, obj, operation, faces) => {
        if (operation) emitSeam(env, { seam: 'meter', operation, shape: 'anon-sandbox' })
        return serveFace(request, url, faces || threeFaces(title, obj), face, { cleanPath })
      }

      if (cleanPath === '/statutes') return serve('fn-risk-compliance — statutes (public-law citation records)', ok(listOf(state.statutes)), 'listStatutes')
      if (cleanPath === '/check-runs') return serve('fn-risk-compliance — check runs (labeled demo seed)', ok(listOf(state.checkRuns)), 'listCheckRuns')
      if (cleanPath === '/obligations') return serve('fn-risk-compliance — obligations (labeled demo seed)', ok(listOf(state.obligations)), 'listObligations')
      if (cleanPath === '/icp' || path === '/icp.json') return serve('fn-risk-compliance — icp (G2 coordinates + agent classes)', icpDocument, null)
      if (cleanPath === '/verify') return serve('fn-risk-compliance — run our tests', verifyPage, null)
      if (cleanPath === '/verify/suite') return serve('fn-risk-compliance — the published suite document', suiteDocument, null)

      const statuteMatch = cleanPath.match(/^\/statutes\/([^/]+)$/)
      if (statuteMatch) {
        const { body } = getRecord(state.statutes, decodeURIComponent(statuteMatch[1]), 'statute')
        return serve(`fn-risk-compliance — statute ${statuteMatch[1]}`, body, 'getStatute')
      }
      const checkMatch = cleanPath.match(/^\/checks\/([^/]+)$/)
      if (checkMatch) {
        const { body } = getRecord(state.checks, decodeURIComponent(checkMatch[1]), 'check definition')
        return serve(`fn-risk-compliance — check ${checkMatch[1]}`, body, 'getCheck')
      }
      const runGetMatch = cleanPath.match(/^\/check-runs\/([^/]+)$/)
      if (runGetMatch) {
        const { body } = getRecord(state.checkRuns, decodeURIComponent(runGetMatch[1]), 'check run')
        return serve(`fn-risk-compliance — check run ${runGetMatch[1]}`, body, 'getCheckRun')
      }
      const obMatch = cleanPath.match(/^\/obligations\/([^/]+)$/)
      if (obMatch) {
        const { body } = getRecord(state.obligations, decodeURIComponent(obMatch[1]), 'obligation')
        return serve(`fn-risk-compliance — obligation ${obMatch[1]}`, body, 'getObligation')
      }
    }

    // 6. typed 404 — nothing here was deleted; the route was never written
    return envelopeResponse(
      { type: 'EMPTY', results: [], message: `no route at ${path} — nothing here has been deleted; the route was never written` },
      { status: 404 },
    )
  },
}
