/**
 * worker.js — the fn-strategy wave-zero property: one Workers-shaped fetch
 * handler serving BOTH plies from ONE definition (template spec §3):
 *
 *   data face      GET /plans, /objectives (branching collection),
 *                  /objectives/{id}, /analyses, /analyses/{id}
 *   headless face  POST /objectives, POST /key-results/{id}/progress —
 *                  system-of-record verbs on the SAME collections, same
 *                  envelopes (strategic-planning/OKR system)
 *   machine face   the AXP quartet + probes, generated by the vendored
 *                  axp-faces (pinned apis-ax-axp@2.6.0) — never hand-rolled
 *   MCP door       POST /mcp — the same Nouns/verbs over JSON-RPC (one definition)
 *   verify         GET /verify, /verify/suite.json — "run our tests"
 *   icp            GET /icp.json — the G2 coordinates + agent classes
 *
 * WAVE-ZERO HONESTY, stated once and enforced below:
 *   - every record is labeled synthetic example data (see ./seed.js);
 *   - mutations are per-isolate and ephemeral (disclosed on every response);
 *   - the rate card is a stub (binding: false + statement); the 402 OFFER
 *     boundary is real and probeable, but nothing settles and nothing charges;
 *   - seams (metering / money / traffic events) are EMITTED per template §7.4
 *     — structured events tagged {substrate, projection, motion, operation,
 *     shape, pattern} — but no dashboard, billing, or account surface exists
 *     here, by design.
 */

import { createAxpRoutes } from './axp/routes.js'
import { buildCard } from './axp/card.js'
import { envelopeResponse, ok, empty } from './axp/envelope.js'
import { negotiate, serveFace, AGENT_UA_TOKENS } from './axp/conneg.js'
import { manifest, ORIGIN } from './manifest.js'
import { plans, objectives, analyses } from './seed.js'
import { seamTags } from './substrate.js'

const RETENTION = 'ephemeral — per-isolate memory only; no durability at wave zero'

// ── the card: generator truth + links.verify (spec §4.1) ────────────────────
// The vendored generator does not yet emit links.verify; the template spec
// requires it. Additive extension of the GENERATED card — the quartet itself
// stays generator-emitted, and the gap is filed as a generator issue
// (fix-the-generator law), never patched deeper than this one link.
const card = (() => {
  const c = buildCard(manifest)
  return { ...c, links: { ...c.links, verify: `${ORIGIN}/verify` } }
})()

const axp = createAxpRoutes(manifest)

// ── per-isolate state (the auto-minted anon workspace, §5.2/#17) ────────────
const state = {
  plans: new Map(plans.map((p) => [p.id, structuredClone(p)])),
  objectives: new Map(objectives.map((o) => [o.id, structuredClone(o)])),
  analyses: new Map(analyses.map((a) => [a.id, structuredClone(a)])),
  minted: 0,
}

// ── seams (template §7.4 — emitted, never rendered; no account UI here) ────
function emitSeam(env, event) {
  const line = JSON.stringify({ ...seamTags, ts: new Date().toISOString(), ...event })
  // Wave zero: structured stdout is the seam. A queue binding, when one is
  // attached, receives the same event without a shape change. (In-process
  // test harnesses set globalThis.__SEAM_SILENT to keep their output legible;
  // the events still shape-check because emitSeam still constructs them.)
  if (globalThis.__SEAM_SILENT !== true) console.log(line)
  if (env && env.SEAMS && typeof env.SEAMS.send === 'function') {
    try {
      env.SEAMS.send(JSON.parse(line))
    } catch {
      /* the seam is best-effort transport, never a request failure */
    }
  }
}

function identityClass(request) {
  // id.org.ai grain is not wired at wave zero — only the CLASS is derivable.
  const mode = request.headers.get('sec-fetch-mode')
  const dest = request.headers.get('sec-fetch-dest')
  if (mode === 'navigate' || dest === 'document') return 'human-browser'
  const ua = (request.headers.get('user-agent') || '').toLowerCase()
  if (AGENT_UA_TOKENS.some((t) => ua.includes(t))) return 'machine-agent'
  return 'machine-unattributed'
}

// ── three-faced serving for this worker's own GET addresses ────────────────
function threeFaces(title, obj) {
  const json = obj
  const md = `# ${title}\n\n\`\`\`json\n${JSON.stringify(obj, null, 2)}\n\`\`\`\n`
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const html = `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><title>${esc(title)}</title></head>\n<body><h1>${esc(title)}</h1><pre>${esc(JSON.stringify(obj, null, 2))}</pre></body></html>\n`
  return { json, md, html }
}

// ── the ICP document: the row's G2 coordinates, exposed (stake #6) ──────────
const icpDocument = {
  $context: 'https://schema.org.ai',
  property: 'fn-strategy.org.ai',
  substrate: 'fn-strategy',
  g2: {
    icp: {
      companyTypes: ['all — horizontal Function row'],
      jobTypes: ['founder', 'chief executive', 'strategy officer', 'chief of staff'],
    },
    coordinates: ['Function=Strategy', 'Department=Executive'],
    personas: [
      { id: 'founder-operator', description: 'founder/CEO steering an annual-or-episodic planning cycle' },
      { id: 'strategy-officer', description: 'strategy/chief-of-staff role running the objective and analysis cadence' },
      { id: 'agent-caller', description: 'autonomous agent consuming plan/objective/analysis records over this machine face (B2A)' },
    ],
  },
  system: { system: 'StrategicPlanning', coordinates: ['Function=Strategy', 'Department=Executive'] },
  agent_classes: [
    { id: 'reader-agent', description: 'keyless reads: the quartet, /plans, /objectives, /analyses, /verify — no key, no account' },
    {
      id: 'sandbox-transactor',
      description:
        'exercises the headless doors (POST /objectives, POST /key-results/{id}/progress) against labeled synthetic state; ' +
        'mutations are per-isolate and ephemeral at wave zero',
    },
    { id: 'mcp-caller', description: 'the same Nouns and verbs over the /mcp JSON-RPC door — one definition, two transports' },
  ],
}

// ── the published suite (links.verify target) ───────────────────────────────
// interfaces.testSuite is deliberately NOT declared on the card: declaring it
// arms check-capability-coverage, which the deployed verifier (autonomous-qa
// 0.3.0) does not implement — a declaration today fails closed on a check the
// verifier cannot produce (the api.lawyer reference posture). The suite still
// ships and links.verify names it: "trust us" → "run this".
const suiteDocument = {
  $type: 'VerifySuite',
  property: 'fn-strategy.org.ai',
  version: '0.1.0',
  runner: 'node selfcheck.mjs (repo: examples/fn-strategy — fail-closed, digest-pinned)',
  pinnedSpec: 'apis-ax-axp@2.6.0',
  pinnedSpecDigest: 'a9a1197c439d708b4db54f606f07c9a2d019c7f2989fbcd9b599de2fcc028e0d',
  tests: [
    { id: 'vendored-pins', asserts: 'every vendored axp-faces file is byte-identical to its VENDORED.json digest; the PINS.json spec digest equals the ratified pin' },
    { id: 'pinned-conformance', asserts: 'gradePinned(worker) passes the pinned apis-ax-axp@2.6.0 spec (runnable view) in-process' },
    { id: 'seed-labeled', asserts: 'every seed record carries example: true and a [demo] title; fictional names only' },
    { id: 'operations-exercised', asserts: 'every declared operation answers substantively against the seed (no ghost surfaces)' },
    { id: 'conneg-matrix', asserts: 'bare curl → JSON; Accept: text/markdown → md; browser navigation → HTML, on this worker’s own addresses' },
    { id: 'offer-ladder', asserts: 'the 402 OFFER at /offer carries the pay/work/claim alternatives, every rung labeled a stub' },
    { id: 'head-mirrors-get', asserts: 'HEAD answers wherever GET answers, same status and headers' },
    { id: 'typed-405', asserts: 'non-GET on a GET-only AXP address answers a typed BLOCKED envelope with Allow' },
  ],
}

const verifyPage = {
  title: 'fn-strategy.org.ai — run our tests',
  body:
    'The published verification suite for this surface. Every claim the machine face makes is checked by a runnable test, ' +
    'not an adjective: the suite document at /verify/suite.json lists each check; the runner is selfcheck.mjs beside this ' +
    'worker in its repository, fail-closed against the pinned apis-ax-axp@2.6.0 spec (digest a9a1197c…). Independent verdict: ' +
    'https://api.qa/fn-strategy.org.ai.',
  suite: `${ORIGIN}/verify/suite.json`,
  conformance: 'https://api.qa/fn-strategy.org.ai',
}

// ── domain views (typed envelopes; the record IS the wire truth) ────────────
const listOf = (map) => [...map.values()]

function getRecord(map, id, what) {
  const rec = map.get(id)
  if (rec === undefined) return { status: 200, body: empty(`no ${what} with id ${id} — a truthful empty result, not an error`) }
  return { status: 200, body: ok([rec]) }
}

// ── MCP (same definition, JSON-RPC transport) ───────────────────────────────
const mcpTools = {
  listPlans: { description: 'List strategic plans (labeled demo seed)', input: {}, call: () => listOf(state.plans) },
  getPlan: { description: 'Get one plan by id', input: { planId: 'string' }, call: (a) => state.plans.get(String(a.planId)) ?? null },
  listObjectives: {
    description: 'List objectives; optional filters cycle, status',
    input: { cycle: 'string?', status: 'string?' },
    call: (a) => listOf(state.objectives).filter((o) => (a.cycle ? o.cycle === a.cycle : true) && (a.status ? o.status === a.status : true)),
  },
  getObjective: { description: 'Get one objective (with key results) by id', input: { objectiveId: 'string' }, call: (a) => state.objectives.get(String(a.objectiveId)) ?? null },
  listAnalyses: { description: 'List analysis records (labeled demo seed)', input: {}, call: () => listOf(state.analyses) },
  getAnalysis: { description: 'Get one analysis by id', input: { analysisId: 'string' }, call: (a) => state.analyses.get(String(a.analysisId)) ?? null },
}

function mcpResponse(id, result) {
  return new Response(JSON.stringify({ jsonrpc: '2.0', id, result }), { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } })
}
function mcpError(id, code, message) {
  return new Response(JSON.stringify({ jsonrpc: '2.0', id, error: { code, message } }), { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } })
}

async function handleMcp(request, env) {
  let msg
  try {
    msg = await request.json()
  } catch {
    return mcpError(null, -32700, 'parse error — the /mcp door speaks JSON-RPC 2.0')
  }
  const { id = null, method, params = {} } = msg || {}
  if (method === 'initialize') {
    return mcpResponse(id, {
      protocolVersion: '2024-11-05',
      capabilities: { tools: {} },
      serverInfo: { name: 'fn-strategy.org.ai', version: '0.1.0' },
    })
  }
  if (method === 'notifications/initialized') return new Response(null, { status: 202 })
  if (method === 'tools/list') {
    return mcpResponse(id, {
      tools: Object.entries(mcpTools).map(([name, t]) => ({
        name,
        description: t.description,
        inputSchema: { type: 'object', properties: Object.fromEntries(Object.entries(t.input).map(([k, v]) => [k, { type: String(v).replace('?', '') }])) },
      })),
    })
  }
  if (method === 'tools/call') {
    const tool = mcpTools[params.name]
    if (!tool) return mcpError(id, -32602, `unknown tool ${JSON.stringify(params.name)} — tools/list names every tool that exists`)
    emitSeam(env, { seam: 'meter', operation: params.name, shape: 'anon-sandbox', transport: 'mcp' })
    const result = tool.call(params.arguments || {})
    return mcpResponse(id, { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }], isError: false })
  }
  return mcpError(id, -32601, `method ${JSON.stringify(method)} is not served — this door answers initialize, tools/list, tools/call`)
}

// ── router ──────────────────────────────────────────────────────────────────
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const path = url.pathname
    const method = request.method

    emitSeam(env, {
      seam: 'traffic',
      path,
      method,
      identity: null, // id.org.ai grain not wired at wave zero — class only
      identityClass: identityClass(request),
      referral: request.headers.get('referer') || null,
    })

    // 1. the card, extended with links.verify (see the header note)
    if (path === '/.well-known/agents.json' && (method === 'GET' || method === 'HEAD')) {
      return new Response(method === 'HEAD' ? null : JSON.stringify(card, null, 2), {
        status: 200,
        headers: { 'content-type': 'application/json; charset=utf-8' },
      })
    }

    // 2. headless doors on collection paths BEFORE the generator (its mounted
    //    paths answer 405 to non-GET; these two POSTs are real doors)
    if (path === '/objectives' && method === 'POST') {
      let input
      try {
        input = await request.json()
      } catch {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the create door takes a JSON body: { title, cycle, planId? }' }, { status: 403 })
      }
      if (!input || typeof input.title !== 'string' || typeof input.cycle !== 'string') {
        return envelopeResponse({ type: 'BLOCKED', reason: 'title and cycle are required — { title, cycle, planId? }' }, { status: 403 })
      }
      state.minted += 1
      const rec = {
        id: `obj-anon-${state.minted}`,
        $type: 'https://schema.org.ai/Objective',
        example: true, // everything minted in the anon sandbox is example data by definition
        title: input.title.startsWith('[demo]') ? input.title : `[demo] ${input.title}`,
        planId: typeof input.planId === 'string' ? input.planId : null,
        cycle: input.cycle,
        status: 'draft',
        keyResults: [],
        workspace: 'anon',
        retention: RETENTION,
      }
      state.objectives.set(rec.id, rec)
      emitSeam(env, { seam: 'meter', operation: 'createObjective', shape: 'anon-sandbox' })
      return envelopeResponse(ok([rec], { extra: { retention: RETENTION } }), { status: 201 })
    }

    const progressMatch = path.match(/^\/key-results\/([^/]+)\/progress$/)
    if (progressMatch && method === 'POST') {
      let input
      try {
        input = await request.json()
      } catch {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the progress door takes a JSON body: { current }' }, { status: 403 })
      }
      if (!input || typeof input.current !== 'number') {
        return envelopeResponse({ type: 'BLOCKED', reason: 'current (number) is required — { current }' }, { status: 403 })
      }
      const krId = decodeURIComponent(progressMatch[1])
      for (const obj of state.objectives.values()) {
        const kr = (obj.keyResults || []).find((k) => k.id === krId)
        if (kr) {
          kr.current = input.current
          emitSeam(env, { seam: 'meter', operation: 'recordKeyResultProgress', shape: 'anon-sandbox' })
          return envelopeResponse(ok([{ objectiveId: obj.id, keyResult: kr }], { extra: { retention: RETENTION } }))
        }
      }
      return envelopeResponse(empty(`no key result with id ${krId} — a truthful empty result, not an error`))
    }

    // 3. the MCP door
    if (path === '/mcp') {
      if (method !== 'POST') {
        return envelopeResponse({ type: 'BLOCKED', reason: 'the /mcp door speaks JSON-RPC 2.0 over POST' }, { status: 405, headers: { allow: 'POST' } })
      }
      return handleMcp(request, env)
    }

    // 4. the generated machine face (quartet, branching collection, offer, home)
    const hit = await axp(request, env)
    if (hit !== undefined) {
      if (path === manifest.collection.path && method === 'GET') {
        emitSeam(env, { seam: 'meter', operation: 'listObjectives', shape: 'anon-sandbox' })
      }
      if (hit.status === 402) {
        // money seam: an OFFER was presented. Nothing settles at wave zero —
        // the event exists so the rail ledger can count the boundary.
        emitSeam(env, { seam: 'money', event: 'offer-presented', operation: path === manifest.pricing.offerPath ? 'getOffer' : 'listObjectives', settlement: 'none — stub rate card' })
      }
      return hit
    }

    // 5. this worker's own GET addresses (conneg-served, three faces)
    if (method === 'GET' || method === 'HEAD') {
      const { face, cleanPath } = negotiate(request, path)

      const serve = (title, obj, operation, faces) => {
        if (operation) emitSeam(env, { seam: 'meter', operation, shape: 'anon-sandbox' })
        return serveFace(request, url, faces || threeFaces(title, obj), face, { cleanPath })
      }

      if (cleanPath === '/plans') return serve('fn-strategy — plans (labeled demo seed)', ok(listOf(state.plans)), 'listPlans')
      if (cleanPath === '/analyses') return serve('fn-strategy — analyses (labeled demo seed)', ok(listOf(state.analyses)), 'listAnalyses')
      if (cleanPath === '/icp' || path === '/icp.json') return serve('fn-strategy — icp (G2 coordinates + agent classes)', icpDocument, null)
      if (cleanPath === '/verify') return serve('fn-strategy — run our tests', verifyPage, null)
      if (cleanPath === '/verify/suite') return serve('fn-strategy — the published suite document', suiteDocument, null)

      const planMatch = cleanPath.match(/^\/plans\/([^/]+)$/)
      if (planMatch) {
        const { body } = getRecord(state.plans, decodeURIComponent(planMatch[1]), 'plan')
        return serve(`fn-strategy — plan ${planMatch[1]}`, body, 'getPlan')
      }
      const objMatch = cleanPath.match(/^\/objectives\/([^/]+)$/)
      if (objMatch) {
        const { body } = getRecord(state.objectives, decodeURIComponent(objMatch[1]), 'objective')
        return serve(`fn-strategy — objective ${objMatch[1]}`, body, 'getObjective')
      }
      const anMatch = cleanPath.match(/^\/analyses\/([^/]+)$/)
      if (anMatch) {
        const { body } = getRecord(state.analyses, decodeURIComponent(anMatch[1]), 'analysis')
        return serve(`fn-strategy — analysis ${anMatch[1]}`, body, 'getAnalysis')
      }
    }

    // 6. typed 404 — nothing here was deleted; the route was never written
    return envelopeResponse(
      { type: 'EMPTY', results: [], message: `no route at ${path} — nothing here has been deleted; the route was never written` },
      { status: 404 },
    )
  },
}
