/**
 * worker.js — monthend.finance, wave zero (register row fn-finance).
 *
 * One substrate, two faces from ONE manifest (template spec §3): the data
 * face (/ledgers, /close-deliverables — typed records from the row's
 * schemas) and the headless face (the same collections as the Accounting
 * system door at coordinate Accounting⟨finance-departments⟩, plus the
 * per-outcome order verb). There is no second API.
 *
 * The AXP quartet + branching collection + conneg home are generated by the
 * vendored axp-faces (PINS.json digest) — never hand-rolled. This file only
 * composes and adds the extra live doors the manifest declares.
 */

import { createAxpRoutes, ok, empty, envelopeResponse, offer } from "./axp/index.js";
import { manifest, icpDoc } from "./manifest.js";
import { ledgers, getLedger, getCloseDeliverable, EXAMPLE_NOTE } from "./seed.js";
import { verifyRoutes } from "./verify.js";
import { emitMeter, emitReceipt, emitSignal } from "./seams.js";

const axp = createAxpRoutes(manifest);

const JSON_CT = { "content-type": "application/json; charset=utf-8" };

function json(obj, { status = 200, head = false } = {}) {
  return new Response(head ? null : JSON.stringify(obj, null, 2), { status, headers: JSON_CT });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const head = request.method === "HEAD";

    // ── the generated faces first (quartet, collection, offer, home, family) ──
    const hit = await axp(request, env);
    if (hit !== undefined) {
      if (path === manifest.collection.path) emitMeter(env, { operation: "listCloseDeliverables" });
      if (path === "/" || path === "/index.html") emitSignal(env, request, { surface: "home" });
      return hit;
    }

    // ── extra live doors (every one declared in the manifest routes) ─────────
    if (request.method === "GET" || head) {
      if (path === "/ledgers") {
        emitMeter(env, { operation: "listLedgers" });
        return json(ok(ledgers, { memberName: "ledgers" }), { head });
      }

      const ledgerMatch = path.match(/^\/ledgers\/([A-Za-z0-9_-]+)$/);
      if (ledgerMatch) {
        emitMeter(env, { operation: "getLedger" });
        const ledger = getLedger(ledgerMatch[1]);
        if (!ledger) return json(empty(`no ledger '${ledgerMatch[1]}' is visible to this caller — an honest miss, not an error page`, { memberName: "ledgers" }), { status: 404, head });
        return json({ type: "OK", ledger }, { head });
      }

      const cdMatch = path.match(/^\/close-deliverables\/([A-Za-z0-9_-]+)$/);
      if (cdMatch) {
        emitMeter(env, { operation: "getCloseDeliverable" });
        const deliverable = getCloseDeliverable(cdMatch[1]);
        if (!deliverable) return json(empty(`no close deliverable '${cdMatch[1]}' exists in this workspace`, { memberName: "deliverables" }), { status: 404, head });
        return json({ type: "OK", deliverable }, { head });
      }

      // rates[] rides TOP-LEVEL in the generated /pricing document
      // (axp-ext-rates-g2 §2) — the former sibling /rates door is gone.
      if (path === "/icp.json") return json(icpDoc, { head });
      if (path === "/healthz") return json(ok([{ status: "ok", sandbox: "anon", note: EXAMPLE_NOTE }]), { head });

      const v = await verifyRoutes(request, url);
      if (v !== undefined) return v;
    }

    // ── the per-outcome order door: a typed 402 OFFER; wave-zero labeled stub ──
    if (path === "/orders" && request.method === "POST") {
      emitMeter(env, { operation: "orderCloseDeliverable", shape: "paid-402" });
      emitReceipt(env, { operation: "orderCloseDeliverable", offerId: "close-deliverable-outcome" });
      return envelopeResponse(
        offer({
          ...manifest.pricing.offers[0],
          message:
            "Ordering a completed close deliverable is the payable outcome door. Wave zero is test-mode: this " +
            "402 is a labeled stub — no billing occurs. The alternatives carry every rung: pay, work, claim, or the human door.",
        }),
        { status: 402 },
      );
    }

    return envelopeResponse(
      empty(`nothing is served at ${request.method} ${path} — the contract at /openapi.json lists every live door`),
      { status: 404 },
    );
  },
};
