export { crudConvention } from './crud'
export { proxyConvention } from './proxy'
export { rpcConvention } from './rpc'
export { mcpConvention } from './mcp'
export { analyticsMiddleware, analyticsRoutes } from './analytics'
export { testingConvention, type TestingConfig, type TestCase, type RestTestCase, type Example } from './testing'
