/**
 * ingest-awards.mjs — the Class-A ingest step for the Award noun (register
 * row public-admin, source route: public-licensable ingest end to end —
 * SAM / USAspending / SoS).
 *
 * Fetches a small corpus of REAL federal contract awards from the
 * USAspending API (U.S. government work — public domain, no key required)
 * and writes seed-awards.js: a versioned module with full provenance on the
 * corpus and on every record. Re-running is the reseed build step (§5.2.5).
 *
 * This is the only REAL-data noun at wave zero. Registration / Filing /
 * Permit records stay synthetic: FinCEN BOI data is confidential by law
 * (never ingestable), state SoS and county permit portals are not
 * mechanically reachable as one keyless Class-A route in-session.
 *
 * Run: node scripts/ingest-awards.mjs
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "seed-awards.js");
const ENDPOINT = "https://api.usaspending.gov/api/v2/search/spending_by_award/";

const body = {
  filters: {
    award_type_codes: ["A", "B", "C", "D"], // contracts
    time_period: [{ start_date: "2026-01-01", end_date: "2026-06-30" }],
  },
  fields: [
    "Award ID",
    "Recipient Name",
    "Award Amount",
    "Awarding Agency",
    "Awarding Sub Agency",
    "Start Date",
    "End Date",
    "Description",
    "recipient_id",
    "generated_internal_id",
  ],
  sort: "Award Amount",
  order: "desc",
  limit: 12,
  page: 1,
};

const res = await fetch(ENDPOINT, {
  method: "POST",
  headers: { "content-type": "application/json" },
  body: JSON.stringify(body),
});
if (!res.ok) throw new Error(`USAspending answered ${res.status} — ingest aborted, seed-awards.js left unchanged`);
const data = await res.json();
const retrievedAt = new Date().toISOString();

const awards = (data.results || []).map((r, i) => ({
  $type: "Award",
  id: `awd_usaspending_${String(i + 1).padStart(2, "0")}`,
  piid: r["Award ID"],
  recipient: r["Recipient Name"],
  amount: r["Award Amount"],
  awardingAgency: r["Awarding Agency"],
  awardingSubAgency: r["Awarding Sub Agency"],
  startDate: r["Start Date"],
  endDate: r["End Date"],
  description: r["Description"],
  usaspendingId: r["generated_internal_id"],
  source: "USAspending",
  real: true,
  provenance: {
    kind: "ingested",
    source: ENDPOINT,
    retrievedAt,
    license: "U.S. government work — public domain (17 U.S.C. § 105)",
    note: "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs.",
  },
}));

if (awards.length === 0) throw new Error("ingest returned zero awards — refusing to write an empty corpus");

const moduleText = `/**
 * seed-awards.js — GENERATED by scripts/ingest-awards.mjs (do not hand-edit;
 * re-run the script to refresh). REAL public data, ingested — the Award
 * noun's Class-A corpus (USAspending, public domain). Every record carries
 * its provenance; nothing here is synthetic and nothing is labeled example.
 */

export const AWARDS_PROVENANCE = Object.freeze(${JSON.stringify(
  {
    source: ENDPOINT,
    query: body.filters,
    retrievedAt,
    records: awards.length,
    license: "U.S. government work — public domain (17 U.S.C. § 105)",
  },
  null,
  2,
)});

export const awards = ${JSON.stringify(awards, null, 2)};
`;

writeFileSync(OUT, moduleText);
console.log(`wrote ${OUT} — ${awards.length} real awards, retrieved ${retrievedAt}`);
