/**
 * facilities.real.mjs — GENERATED by scripts/ingest-facilities.mjs (do not
 * hand-edit; re-run the script to refresh). REAL public data, ingested —
 * the Facility noun's Class-A corpus (EPA ECHO RCRA handler search, public
 * domain). Every record carries its provenance; nothing here is synthetic
 * and nothing is labeled example. Synthetic sandbox records (seed.mjs)
 * deliberately never reference these real parties.
 */

export const FACILITIES_PROVENANCE = Object.freeze({
  "kind": "ingested",
  "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
  "query": {
    "p_st": "TX",
    "p_act": "Y"
  },
  "retrievedAt": "2026-08-23T20:41:39.839Z",
  "license": "U.S. government work — public domain (17 U.S.C. § 105)",
  "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
});

export const facilities = [
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000068346",
    "handlerId": "TXR000068346",
    "frsRegistryId": "110024545599",
    "name": "1 CHEYENNE MANAGEMENT & ENVIRONMENTAL SE",
    "street": "2449 HOUSTON SUITE 100",
    "city": "GRAND PRAIRIE",
    "county": "DALLAS",
    "state": "TX",
    "zip": "75050",
    "epaRegion": "06",
    "naics": "562998",
    "universe": "Transporter",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "32.74088",
    "long": "-97.04154",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000071225",
    "handlerId": "TXR000071225",
    "frsRegistryId": "110031357680",
    "name": "1.19 SUPER CLEANERS",
    "street": "1910 S DAIRY ASHFORD",
    "city": "HOUSTON",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77077",
    "epaRegion": "06",
    "naics": null,
    "universe": "VSQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "29.746014",
    "long": "-95.606127",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000070359",
    "handlerId": "TXR000070359",
    "frsRegistryId": "110031349146",
    "name": "1.25 ANTOINE CLEANERS",
    "street": "8124 ANTOINE DR",
    "city": "HOUSTON",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77088",
    "epaRegion": "06",
    "naics": null,
    "universe": "VSQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "29.885492",
    "long": "-95.47389",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000070565",
    "handlerId": "TXR000070565",
    "frsRegistryId": "110031376464",
    "name": "1.25 BRIAN CLEANERS",
    "street": "3301 TIDWELL RD",
    "city": "HOUSTON",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77093",
    "epaRegion": "06",
    "naics": null,
    "universe": "VSQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "29.84871",
    "long": "-95.33606",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000070284",
    "handlerId": "TXR000070284",
    "frsRegistryId": "110031330575",
    "name": "1.25 CLEANERS",
    "street": "12704 GRANT RD",
    "city": "CYPRESS",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77429",
    "epaRegion": "06",
    "naics": null,
    "universe": "VSQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "29.989206",
    "long": "-95.617149",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXD988083838",
    "handlerId": "TXD988083838",
    "frsRegistryId": "110005157169",
    "name": "1.25 CLEANERS",
    "street": "581 W CAMPBELL RD",
    "city": "RICHARDSON",
    "county": "DALLAS",
    "state": "TX",
    "zip": "75080",
    "epaRegion": "06",
    "naics": null,
    "universe": "SQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "32.9779",
    "long": "-96.73935",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000071498",
    "handlerId": "TXR000071498",
    "frsRegistryId": "110031301044",
    "name": "1.25 CLEANERS",
    "street": "4939 FM 2920",
    "city": "SPRING",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77388",
    "epaRegion": "06",
    "naics": null,
    "universe": "VSQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "30.073734",
    "long": "-95.49433",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000006114",
    "handlerId": "TXR000006114",
    "frsRegistryId": "110005166792",
    "name": "1.25 DRY CLEAN SUPER CENTER",
    "street": "900 N ELDRIDGE",
    "city": "HOUSTON",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77079",
    "epaRegion": "06",
    "naics": "81232",
    "universe": "SQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "29.78157",
    "long": "-95.61721",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000070250",
    "handlerId": "TXR000070250",
    "frsRegistryId": "110031349173",
    "name": "1.25 DRY CLEAN SUPERCENTER",
    "street": "11422 LOUETTA RD",
    "city": "HOUSTON",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77070",
    "epaRegion": "06",
    "naics": null,
    "universe": "VSQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "29.99674",
    "long": "-95.59106",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  },
  {
    "$type": "https://schema.org.ai/Facility",
    "id": "fac_echo_TXR000070268",
    "handlerId": "TXR000070268",
    "frsRegistryId": "110031330147",
    "name": "1.25 DRY CLEAN WORLD",
    "street": "121209 FM 1960 RD STE A",
    "city": "HOUSTON",
    "county": "HARRIS",
    "state": "TX",
    "zip": "77065",
    "epaRegion": "06",
    "naics": null,
    "universe": "VSQG",
    "rcraStatus": "Active (H    )",
    "complianceStatus": "No Violation Identified",
    "snc": "No",
    "inspectionCount": "0",
    "lat": "29.924185",
    "long": "-95.599751",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://echodata.epa.gov/echo/rcra_rest_services.get_facilities",
      "query": {
        "p_st": "TX",
        "p_act": "Y"
      },
      "retrievedAt": "2026-08-23T20:41:39.839Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public RCRA handler records ingested from EPA ECHO. Not synthetic, not example-labeled. Fields are as published by the source at retrievedAt; refresh via scripts/ingest-facilities.mjs."
    }
  }
];
