/**
 * worker.js — apis.finance, wave zero (register row banking-payments).
 *
 * One substrate, two faces from ONE manifest (template spec §3): the data
 * face (/payment-messages, /loans, /credit-files, /lenders — typed records
 * from the row's schemas, ISO 20022 interchange spine) and the headless face
 * (the core-banking system-of-record door at coordinate
 * CoreBanking⟨banks, credit-unions, non-bank-lenders, fintech-loan-servicers⟩:
 * the workspace mint + register verbs, plus the payable pull/origination
 * doors). There is no second API. The MCP door serves the same Nouns/verbs.
 *
 * The AXP quartet + branching collection + conneg home are generated by the
 * vendored axp-faces (PINS.json digest) — never hand-rolled. The batch-2
 * ruled extension placements (rates[] top-level in /pricing, g2 + links.verify
 * on the card, operationId on every route) are bridged in bridge.js, which
 * runs FIRST so the extended documents shadow the generator's unextended
 * output. This file only composes and adds the extra live doors the manifest
 * declares.
 */

import { createAxpRoutes, ok, empty, envelopeResponse, offer } from "./axp/index.js";
import { manifest, icpDoc } from "./manifest.js";
import { bridgedRoutes } from "./bridge.js";
import {
  loans, getLoan, creditFiles, getCreditFile, lenders, getLender,
  getPaymentMessage, EXAMPLE_NOTE,
} from "./seed.js";
import { verifyRoutes } from "./verify.js";
import { mcpRoutes } from "./mcp.js";
import { emitMeter, emitReceipt, emitSignal } from "./seams.js";

const axp = createAxpRoutes(manifest);

const JSON_CT = { "content-type": "application/json; charset=utf-8" };

function json(obj, { status = 200, head = false } = {}) {
  return new Response(head ? null : JSON.stringify(obj, null, 2), { status, headers: JSON_CT });
}

/** The wave-zero stub 402 body for a payable door — mounted rungs only. */
function payableOffer(message) {
  return offer({ ...manifest.pricing.offers[0], message });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const head = request.method === "HEAD";

    // ── the bridged documents FIRST (batch-2 ruled placements) ──────────────
    const bridged = bridgedRoutes(request);
    if (bridged !== undefined) {
      if (path.startsWith("/pricing")) emitMeter(env, { operation: "getPricing" });
      return bridged;
    }

    // ── the generated faces (collection, llms.txt, offer, family, home) ─────
    const hit = await axp(request, env);
    if (hit !== undefined) {
      if (path === manifest.collection.path) emitMeter(env, { operation: "listPaymentMessages" });
      if (path === "/" || path === "/index.html") emitSignal(env, request, { surface: "home" });
      return hit;
    }

    // ── the MCP door (sandbox tools authless; payable tools bearer-keyed) ───
    const mcpHit = await mcpRoutes(request, url);
    if (mcpHit !== undefined) {
      emitMeter(env, { operation: "mcp" });
      return mcpHit;
    }

    // ── extra live doors (every one declared in the manifest routes) ────────
    if (request.method === "GET" || head) {
      const pmMatch = path.match(/^\/payment-messages\/([A-Za-z0-9._-]+)$/);
      if (pmMatch) {
        emitMeter(env, { operation: "getPaymentMessage" });
        const message = getPaymentMessage(pmMatch[1]);
        if (!message) return json(empty(`no payment message '${pmMatch[1]}' exists in this workspace`, { memberName: "messages" }), { status: 404, head });
        return json({ type: "OK", message }, { head });
      }

      if (path === "/loans") {
        emitMeter(env, { operation: "listLoans" });
        return json(ok(loans, { memberName: "loans" }), { head });
      }
      const loanMatch = path.match(/^\/loans\/([A-Za-z0-9_-]+)$/);
      if (loanMatch) {
        emitMeter(env, { operation: "getLoan" });
        const loan = getLoan(loanMatch[1]);
        if (!loan) return json(empty(`no loan '${loanMatch[1]}' is visible to this caller — an honest miss, not an error page`, { memberName: "loans" }), { status: 404, head });
        return json({ type: "OK", loan }, { head });
      }

      if (path === "/credit-files") {
        emitMeter(env, { operation: "listCreditFiles" });
        return json(ok(creditFiles, { memberName: "files" }), { head });
      }
      const cfMatch = path.match(/^\/credit-files\/([A-Za-z0-9_-]+)$/);
      if (cfMatch) {
        emitMeter(env, { operation: "getCreditFile" });
        const file = getCreditFile(cfMatch[1]);
        if (!file) return json(empty(`no credit file '${cfMatch[1]}' exists in this workspace`, { memberName: "files" }), { status: 404, head });
        return json({ type: "OK", file }, { head });
      }

      if (path === "/lenders") {
        emitMeter(env, { operation: "listLenders" });
        return json(ok(lenders, { memberName: "lenders" }), { head });
      }
      const lenderMatch = path.match(/^\/lenders\/([A-Za-z0-9_-]+)$/);
      if (lenderMatch) {
        emitMeter(env, { operation: "getLender" });
        const lender = getLender(lenderMatch[1]);
        if (!lender) return json(empty(`no lender '${lenderMatch[1]}' exists in this register`, { memberName: "lenders" }), { status: 404, head });
        return json({ type: "OK", lender }, { head });
      }

      const wsMatch = path.match(/^\/workspaces\/([A-Za-z0-9_-]+)$/);
      if (wsMatch) {
        emitMeter(env, { operation: "getWorkspace" });
        return json(
          empty(
            `no workspace '${wsMatch[1]}' is available — wave-zero workspaces are EPHEMERAL (disclosed on mint): nothing persists between requests; re-mint at POST /workspaces`,
            { memberName: "workspaces" },
          ),
          { status: 404, head },
        );
      }

      if (path === "/icp.json") {
        emitMeter(env, { operation: "getICP" });
        return json(icpDoc, { head });
      }
      if (path === "/healthz") return json(ok([{ status: "ok", sandbox: "anon", note: EXAMPLE_NOTE }]), { head });

      const v = await verifyRoutes(request, url);
      if (v !== undefined) return v;
    }

    // ── the payable doors: typed 402 OFFERs; wave-zero labeled stubs ────────
    if (path === "/credit-files/pulls" && request.method === "POST") {
      emitMeter(env, { operation: "pullCreditFile", shape: "paid-402" });
      emitReceipt(env, { operation: "pullCreditFile", offerId: "lending-system-calls" });
      return envelopeResponse(
        payableOffer(
          "Pulling a consented commercial credit file is the payable records-floor door ('Agents can't grant " +
            "credit. They can pull the file.'). Wave zero is test-mode: this 402 is a labeled stub — no billing " +
            "occurs and no pull is performed. Alternatives list mounted rungs only.",
        ),
        { status: 402 },
      );
    }

    if (path === "/originations" && request.method === "POST") {
      emitMeter(env, { operation: "submitOrigination", shape: "paid-402" });
      emitReceipt(env, { operation: "submitOrigination", offerId: "lending-system-calls" });
      return envelopeResponse(
        payableOffer(
          "Origination submission is routed to a licensed Lender — the Lender, not this property, grants credit " +
            "(the standing-door pattern). Wave zero is test-mode: this 402 is a labeled stub — no billing occurs " +
            "and nothing is routed. Alternatives list mounted rungs only.",
        ),
        { status: 402 },
      );
    }

    // ── the headless system-of-record doors (workspace mint + register) ─────
    if (path === "/workspaces" && request.method === "POST") {
      emitMeter(env, { operation: "mintWorkspace" });
      emitSignal(env, request, { surface: "workspace-mint" });
      const id = `ws_anon_${crypto.randomUUID().slice(0, 8)}`;
      return json(
        ok(
          [
            {
              $type: "Workspace",
              id,
              tenant: "anonymous",
              minted: new Date().toISOString(),
              retention:
                "EPHEMERAL at wave zero: this workspace exists only in this response — nothing you send is stored; " +
                "durable auto-minted workspaces land with the platform workspace door and will disclose their tenure",
              doors: { registerLoan: `/workspaces/${id}/loans` },
              example: false,
              note: "a real minted workspace envelope — over no persisted state; the retention line is the disclosure",
            },
          ],
          { memberName: "workspaces" },
        ),
      );
    }

    const wsLoanMatch = path.match(/^\/workspaces\/([A-Za-z0-9_-]+)\/loans$/);
    if (wsLoanMatch && request.method === "POST") {
      emitMeter(env, { operation: "registerLoanRecord" });
      let payload;
      try {
        payload = await request.json();
      } catch {
        return json(empty("the loan record must be a JSON body — see /openapi.json for the Loan shape"), { status: 400 });
      }
      const missing = ["borrower", "principal", "annualRatePct", "termMonths"].filter((k) => payload?.[k] === undefined);
      if (missing.length > 0) {
        return json(empty(`the loan record is missing required members: ${missing.join(", ")}`), { status: 400 });
      }
      return json({
        type: "OK",
        loan: {
          $type: "Loan",
          id: `loan_${wsLoanMatch[1]}_${crypto.randomUUID().slice(0, 8)}`,
          workspaceId: wsLoanMatch[1],
          ...payload,
          persisted: false,
          note:
            "validated and echoed — NOT persisted: wave-zero workspaces are ephemeral (disclosed on mint); the " +
            "durable core-banking system-of-record door lands with the platform workspace primitive",
        },
      });
    }

    return envelopeResponse(
      empty(`nothing is served at ${request.method} ${path} — the contract at /openapi.json lists every live door`),
      { status: 404 },
    );
  },
};
