/**
 * MCP Tool Registry
 *
 * Unified registry for MCP tools from all sources:
 * - Explicit MCP config tools (with handlers)
 * - Database convention auto-generated tools (route-only)
 * - Functions convention tools (route-only)
 *
 * The registry ensures all tools are accessible through a single /mcp endpoint.
 *
 * ## Tool Types
 *
 * ### Explicit Tools (with handlers)
 * Tools defined in the `mcp.tools` config with full handler implementations.
 * These can be called directly via MCP `tools/call`.
 *
 * ```typescript
 * mcp: {
 *   tools: [{
 *     name: 'calculate',
 *     handler: async (input) => input.a + input.b,
 *     inputSchema: { type: 'object', properties: { a: { type: 'number' }, b: { type: 'number' } } }
 *   }]
 * }
 * ```
 *
 * ### Route-Only Tools (auto-generated)
 * Tools generated by database and functions conventions. These are registered
 * for discoverability via `tools/list` but must be invoked via their REST endpoints.
 * When called directly via MCP, they return an informative error explaining
 * which REST endpoint to use instead.
 *
 * Auto-generated tools include:
 * - Database CRUD tools: `{entity}.create`, `{entity}.get`, `{entity}.list`, etc.
 * - Functions tools: custom functions defined in the functions convention
 */

import type { Context } from 'hono'
import type { TestCase } from './conventions/testing'

/**
 * Tool definition for the registry (without requiring a handler for listing)
 */
export interface RegistryTool {
  name: string
  description: string
  inputSchema: Record<string, unknown>
  outputSchema?: Record<string, unknown>
  examples?: Array<{ name: string; input?: unknown; output?: unknown }>
  tests?: TestCase[]
  handler?: (input: unknown, c: Context) => Promise<unknown>
  /**
   * When true, this tool is served via REST routes only.
   * Calling this tool directly via MCP tools/call will return an error
   * explaining that the tool should be invoked via the corresponding REST endpoint.
   *
   * This is used for auto-generated tools from database and functions conventions
   * where the actual implementation is in the REST route handlers.
   */
  routeOnly?: boolean
}

/**
 * Unified MCP Tool Registry
 *
 * Collects tools from all conventions and serves them through a single endpoint.
 * Uses "last wins" strategy for duplicate tool names.
 */
export class McpToolRegistry {
  private tools: Map<string, RegistryTool> = new Map()

  /**
   * Register a tool in the registry
   *
   * @param tool - The tool to register
   */
  register(tool: RegistryTool): void {
    this.tools.set(tool.name, tool)
  }

  /**
   * Register multiple tools at once
   *
   * @param tools - Array of tools to register
   */
  registerAll(tools: RegistryTool[]): void {
    for (const tool of tools) {
      this.register(tool)
    }
  }

  /**
   * Get all registered tools
   *
   * @returns Array of all registered tools
   */
  getTools(): RegistryTool[] {
    return Array.from(this.tools.values())
  }

  /**
   * Get a specific tool by name
   *
   * @param name - The tool name to look up
   * @returns The tool if found, undefined otherwise
   */
  getTool(name: string): RegistryTool | undefined {
    return this.tools.get(name)
  }

  /**
   * Check if a tool exists in the registry
   *
   * @param name - The tool name to check
   * @returns true if the tool exists
   */
  hasTool(name: string): boolean {
    return this.tools.has(name)
  }

  /**
   * Get the number of registered tools
   */
  get size(): number {
    return this.tools.size
  }

  /**
   * Clear all registered tools
   */
  clear(): void {
    this.tools.clear()
  }
}

/**
 * Create a new McpToolRegistry instance
 */
export function createMcpToolRegistry(): McpToolRegistry {
  return new McpToolRegistry()
}
