/**
 * seed.js — the §5.2 sandbox seed for the SYNTHETIC nouns (Registration,
 * Filing, Permit). EVERY record here is synthetic and labeled: fictional
 * companies, fictional addresses, no real identifiers — EINs use the 00-
 * prefix the IRS never issues, UEI-shaped ids spell EXAMPLE, and every
 * record carries `example: true`.
 *
 * (The Award noun is NOT here: it is REAL ingested public data —
 * seed-awards.js, generated by scripts/ingest-awards.mjs from USAspending
 * with provenance on every record. Real data is never labeled example;
 * synthetic data always is.)
 *
 * Internal consistency is a property of the generator, not of hand-typed
 * rows: registration statuses derive from renewal dates against a fixed
 * AS_OF date, every Filing references the Registration it discharges, and
 * every renewal-due Registration has exactly one open filing task — the
 * compliance calendar ties by construction, the way a premium back-office
 * example must.
 */

export const AS_OF = "2026-08-23"; // fixed — the seed is deterministic, never Date.now()

export const EXAMPLE_NOTE =
  "Example data — synthetic sandbox seed over fictional companies (Cobble Harbor Builders LLC, " +
  "Bluewell Freight Cooperative, Lanternfield Analytics Inc — all fictional). No real company, person, " +
  "EIN, UEI, or address appears in the synthetic corpus: EINs use the never-issued 00- prefix and " +
  "UEI-shaped ids spell EXAMPLE. Anonymous sandbox: stateless reads; nothing you send is stored at " +
  "wave zero; the seed regenerates on every deploy.";

/** The three fictional registrant companies (the back-office ICP). */
export const companies = [
  {
    $type: "Organization",
    id: "org_cobbleharbor",
    name: "Cobble Harbor Builders LLC (fictional)",
    kind: "construction contractor",
    ein: "00-0000101",
    uei: "EXAMPLE00001",
    stateEntityNo: "X-0000101",
    example: true,
  },
  {
    $type: "Organization",
    id: "org_bluewell",
    name: "Bluewell Freight Cooperative (fictional)",
    kind: "freight carrier",
    ein: "00-0000102",
    uei: "EXAMPLE00002",
    stateEntityNo: "X-0000102",
    example: true,
  },
  {
    $type: "Organization",
    id: "org_lanternfield",
    name: "Lanternfield Analytics Inc (fictional)",
    kind: "government analytics seller",
    ein: "00-0000103",
    uei: "EXAMPLE00003",
    stateEntityNo: "X-0000103",
    example: true,
  },
];

/** Days between AS_OF and an ISO date (positive = future). */
function daysFromAsOf(iso) {
  return Math.round((Date.parse(iso) - Date.parse(AS_OF)) / 86400000);
}

/** Status derives from the renewal date — never hand-typed. */
function statusFor(renewsAt) {
  const d = daysFromAsOf(renewsAt);
  if (d < 0) return "lapsed";
  if (d <= 60) return "renewal-due";
  return "active";
}

/** One registration row: the registrant's standing in one registry. */
function reg(seq, companyId, jurisdiction, registry, registeredAt, renewsAt, extra = {}) {
  const company = companies.find((c) => c.id === companyId);
  return {
    $type: "Registration",
    id: `reg_${String(seq).padStart(2, "0")}_${companyId.replace("org_", "")}_${registry}`,
    companyId,
    company: company.name,
    jurisdiction,
    registry,
    registeredAt,
    renewsAt,
    status: statusFor(renewsAt),
    asOf: AS_OF,
    ...extra,
    example: true,
    exampleNote: EXAMPLE_NOTE,
  };
}

/** The registration corpus — every registrant across its registries. */
export const registrations = [
  // Cobble Harbor Builders — contractor: SAM (bids), state SoS, BOI, county contractor license
  reg(1, "org_cobbleharbor", "federal-sam", "sam-uei", "2024-09-10", "2026-09-10", { uei: "EXAMPLE00001", purpose: "all-awards (bidding)" }),
  reg(2, "org_cobbleharbor", "state-sos", "sos-annual-report", "2023-04-02", "2027-04-02", { stateEntityNo: "X-0000101" }),
  reg(3, "org_cobbleharbor", "fincen-boi", "boi-report", "2024-01-15", "2027-01-15", { note: "initial BOI report on file; update-on-change regime" }),
  reg(4, "org_cobbleharbor", "county-permits", "contractor-license", "2024-08-30", "2026-08-30", {}),
  // Bluewell Freight — carrier: state SoS, BOI, operating authority renewal
  reg(5, "org_bluewell", "state-sos", "sos-annual-report", "2022-11-20", "2026-11-20", { stateEntityNo: "X-0000102" }),
  reg(6, "org_bluewell", "fincen-boi", "boi-report", "2024-03-08", "2026-07-08", { note: "ownership change reported; refile overdue" }),
  reg(7, "org_bluewell", "federal-sam", "sam-uei", "2025-02-14", "2027-02-14", { uei: "EXAMPLE00002", purpose: "financial-assistance only" }),
  // Lanternfield Analytics — govcon seller: SAM, state SoS, BOI
  reg(8, "org_lanternfield", "federal-sam", "sam-uei", "2023-10-05", "2026-10-05", { uei: "EXAMPLE00003", purpose: "all-awards (bidding)" }),
  reg(9, "org_lanternfield", "state-sos", "sos-annual-report", "2021-06-18", "2026-06-18", { stateEntityNo: "X-0000103", note: "annual report window missed" }),
  reg(10, "org_lanternfield", "fincen-boi", "boi-report", "2024-02-01", "2027-02-01", {}),
];

/** Filings derive FROM registrations: one completed artifact per past cycle,
 *  one open task per renewal-due/lapsed registration — never orphaned. */
export const filings = registrations.flatMap((r) => {
  const out = [];
  // the completed artifact from the registration's last cycle
  out.push({
    $type: "Filing",
    id: `fil_done_${r.id.slice(4)}`,
    registrationId: r.id,
    companyId: r.companyId,
    company: r.company,
    jurisdiction: r.jurisdiction,
    registry: r.registry,
    kind:
      r.registry === "sam-uei"
        ? "sam-registration-renewal"
        : r.registry === "sos-annual-report"
          ? "annual-report"
          : r.registry === "boi-report"
            ? "boi-initial-report"
            : "license-application",
    status: "filed",
    filedAt: r.registeredAt,
    example: true,
    exampleNote: EXAMPLE_NOTE,
  });
  // the open task where the calendar says one is due
  if (r.status === "renewal-due" || r.status === "lapsed") {
    out.push({
      $type: "Filing",
      id: `fil_open_${r.id.slice(4)}`,
      registrationId: r.id,
      companyId: r.companyId,
      company: r.company,
      jurisdiction: r.jurisdiction,
      registry: r.registry,
      kind: r.registry === "boi-report" ? "boi-updated-report" : "renewal",
      status: r.status === "lapsed" ? "overdue" : "open",
      dueAt: r.renewsAt,
      example: true,
      exampleNote: EXAMPLE_NOTE,
    });
  }
  return out;
});

/** Permits — the permits.works / permits.casa door's record grain
 *  (fictional project addresses, statuses consistent with their dates). */
export const permits = [
  {
    $type: "Permit",
    id: "prm_01_building",
    companyId: "org_cobbleharbor",
    company: companies[0].name,
    jurisdiction: "county-permits",
    kind: "building",
    project: "14 Harrow Lane (fictional address) — two-story addition",
    status: "issued",
    appliedAt: "2026-05-02",
    issuedAt: "2026-06-11",
    expiresAt: "2027-06-11",
    example: true,
    exampleNote: EXAMPLE_NOTE,
  },
  {
    $type: "Permit",
    id: "prm_02_electrical",
    companyId: "org_cobbleharbor",
    company: companies[0].name,
    jurisdiction: "county-permits",
    kind: "electrical",
    project: "14 Harrow Lane (fictional address) — service upgrade",
    status: "inspection-scheduled",
    appliedAt: "2026-06-20",
    issuedAt: "2026-07-03",
    inspectionAt: "2026-09-04",
    example: true,
    exampleNote: EXAMPLE_NOTE,
  },
  {
    $type: "Permit",
    id: "prm_03_rightofway",
    companyId: "org_cobbleharbor",
    company: companies[0].name,
    jurisdiction: "county-permits",
    kind: "right-of-way",
    project: "Quarry Bend Road frontage (fictional) — curb cut",
    status: "applied",
    appliedAt: "2026-08-14",
    example: true,
    exampleNote: EXAMPLE_NOTE,
  },
  {
    $type: "Permit",
    id: "prm_04_signage",
    companyId: "org_lanternfield",
    company: companies[2].name,
    jurisdiction: "county-permits",
    kind: "signage",
    project: "8 Millbrook Court (fictional address) — office sign",
    status: "issued",
    appliedAt: "2026-03-01",
    issuedAt: "2026-03-19",
    expiresAt: "2031-03-19",
    example: true,
    exampleNote: EXAMPLE_NOTE,
  },
];

export function getRegistration(id) {
  const r = registrations.find((x) => x.id === id);
  if (!r) return undefined;
  return { ...r, filings: filings.filter((f) => f.registrationId === id).map((f) => f.id) };
}

export function getFiling(id) {
  return filings.find((x) => x.id === id);
}

export function getPermit(id) {
  return permits.find((x) => x.id === id);
}
