/**
 * seed-awards.js — GENERATED by scripts/ingest-awards.mjs (do not hand-edit;
 * re-run the script to refresh). REAL public data, ingested — the Award
 * noun's Class-A corpus (USAspending, public domain). Every record carries
 * its provenance; nothing here is synthetic and nothing is labeled example.
 */

export const AWARDS_PROVENANCE = Object.freeze({
  "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
  "query": {
    "award_type_codes": [
      "A",
      "B",
      "C",
      "D"
    ],
    "time_period": [
      {
        "start_date": "2026-01-01",
        "end_date": "2026-06-30"
      }
    ]
  },
  "retrievedAt": "2026-08-23T19:27:20.542Z",
  "records": 12,
  "license": "U.S. government work — public domain (17 U.S.C. § 105)"
});

export const awards = [
  {
    "$type": "Award",
    "id": "awd_usaspending_01",
    "piid": "HT940216C0001",
    "recipient": "HUMANA GOVERNMENT BUSINESS INC",
    "amount": 51269205263.03,
    "awardingAgency": "Department of Defense",
    "awardingSubAgency": "Defense Health Agency",
    "startDate": "2016-08-01",
    "endDate": "2025-12-31",
    "description": "IGF::OT::IGF",
    "usaspendingId": "CONT_AWD_HT940216C0001_9700_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_02",
    "piid": "DEAC0494AL85000",
    "recipient": "LOCKHEED MARTIN CORP",
    "amount": 48063737196.35,
    "awardingAgency": "Department of Energy",
    "awardingSubAgency": "Department of Energy",
    "startDate": "1993-10-15",
    "endDate": "2017-04-30",
    "description": null,
    "usaspendingId": "CONT_AWD_DEAC0494AL85000_8900_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_03",
    "piid": "DENA0003525",
    "recipient": "NATIONAL TECHNOLOGY & ENGINEERING SOLUTIONS OF SANDIA, LLC",
    "amount": 42774168231.25,
    "awardingAgency": "Department of Energy",
    "awardingSubAgency": "Department of Energy",
    "startDate": "2017-01-18",
    "endDate": "2027-04-30",
    "description": "IGF::CL,CT::IGF CONTRACT AWARD DE-NA0003525 TO THE NATIONAL TECHNOLOGY&ENGINEERING SOLUTIONS OF SANDIA, LLC (NTESS) FOR THE MANAGEMENT AND OPERATION OF THE DEPARTMENT OF ENERGY, NATIONAL NUCLEAR SECURITY ADMINISTRATION'S SANDIA NATIONAL LABORATORIES (SNL)",
    "usaspendingId": "CONT_AWD_DENA0003525_8900_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_04",
    "piid": "DEAC0500OR22725",
    "recipient": "UT-BATTELLE LLC",
    "amount": 42257183758.79,
    "awardingAgency": "Department of Energy",
    "awardingSubAgency": "Department of Energy",
    "startDate": "1999-10-15",
    "endDate": "2030-03-31",
    "description": "MANAGEMENT AND OPERATION OF THE OAK RIDGE NATIONAL LABORATORY",
    "usaspendingId": "CONT_AWD_DEAC0500OR22725_8900_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_05",
    "piid": "DEAC5207NA27344",
    "recipient": "LAWRENCE LIVERMORE NATIONAL SECURITY, LLC",
    "amount": 41316801717.75,
    "awardingAgency": "Department of Energy",
    "awardingSubAgency": "Department of Energy",
    "startDate": "2007-05-09",
    "endDate": "2031-09-30",
    "description": "TAS::89 0240::TAS THIS PERFORMANCE-BASED MANAGEMENT CONTRACT (PBMC) IS FOR THE MANAGEMENT AND OPERATION OF THE LAWRENCE LIVERMORE NATIONAL LABORATORY (LLNL). THE CONTRACTOR SHALL, IN ACCORDANCE WITH THE PROVISIONS OF THIS CONTRACT, ACCOMPLISH THE MISSIONS AND PROGRAMS ASSIGNED BY THE U.S. DEPARTMENT OF ENERGY (DOE) AND MANAGE AND OPERATE THE LABORATORY.  THE LABORATORY IS ONE OF DOES OFFICE OF DEFENSE PROGRAM MULTI-PROGRAM LABORATORIES.  THE LABORATORY IS A FEDERALLY FUNDED RESEARCH AND DEVELOPMENT INSTITUTION (ESTABLISHED IN ACCORDANCE WITH THE FEDERAL ACQUISITION REGULATION (FAR) PART 35 AND OPERATED UNDER THIS MANAGEMENT AND OPERATING (M&O) CONTRACT, AS DEFINED IN FAR 17.6 AND DEAR 917.6.",
    "usaspendingId": "CONT_AWD_DEAC5207NA27344_8900_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_06",
    "piid": "DEAC3243AL00036",
    "recipient": "REGENTS OF THE UNIVERSITY OF CALIFORNIA, THE",
    "amount": 35295925219.18,
    "awardingAgency": "Department of Energy",
    "awardingSubAgency": "Department of Energy",
    "startDate": "1978-09-30",
    "endDate": "2006-05-31",
    "description": "M&O OF LANL BR OF U OF CA",
    "usaspendingId": "CONT_AWD_DEAC3243AL00036_8900_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_07",
    "piid": "89233218CNA000001",
    "recipient": "TRIAD NATIONAL SECURITY, LLC",
    "amount": 35144939584.19,
    "awardingAgency": "Department of Energy",
    "awardingSubAgency": "Department of Energy",
    "startDate": "2018-06-08",
    "endDate": "2028-10-31",
    "description": "IGF::CL::IGF COMPETITION FOR MANAGEMENT AND OPERATION OF LOS ALAMOS NATIONAL LABORATORY",
    "usaspendingId": "CONT_AWD_89233218CNA000001_8900_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_08",
    "piid": "N0001917C0001",
    "recipient": "LOCKHEED MARTIN CORPORATION",
    "amount": 35135514910.2,
    "awardingAgency": "Department of Defense",
    "awardingSubAgency": "Department of the Navy",
    "startDate": "2017-11-17",
    "endDate": "2031-03-31",
    "description": "LRIP LOT 12 ADVANCE ACQUISITION CONTRACT",
    "usaspendingId": "CONT_AWD_N0001917C0001_9700_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_09",
    "piid": "N0002417C2100",
    "recipient": "ELECTRIC BOAT CORPORATION",
    "amount": 34923378164,
    "awardingAgency": "Department of Defense",
    "awardingSubAgency": "Department of the Navy",
    "startDate": "2017-02-14",
    "endDate": "2036-06-02",
    "description": "SSN 802 AND 803 LONG LEAD TIME MATERIAL",
    "usaspendingId": "CONT_AWD_N0002417C2100_9700_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_10",
    "piid": "DENA0001942",
    "recipient": "CONSOLIDATED NUCLEAR SECURITY, LLC",
    "amount": 34404438769.98,
    "awardingAgency": "Department of Energy",
    "awardingSubAgency": "Department of Energy",
    "startDate": "2013-01-08",
    "endDate": "2027-09-30",
    "description": "IGF::CL,CT::IGF MANAGEMENT AND OPERATING CONTRACT FOR Y-12 NATIONAL SECURITY COMPLEX, PANTEX PLANT, WITH AN OPTION FOR SAVANNAH RIVER TRITIUM OPERATIONS",
    "usaspendingId": "CONT_AWD_DENA0001942_8900_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_11",
    "piid": "FA862511C6600",
    "recipient": "THE BOEING COMPANY",
    "amount": 31972918249.03,
    "awardingAgency": "Department of Defense",
    "awardingSubAgency": "Department of the Air Force",
    "startDate": "2011-02-24",
    "endDate": "2027-07-31",
    "description": "KC-X MODERNIZATION PROGRAM",
    "usaspendingId": "CONT_AWD_FA862511C6600_9700_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  },
  {
    "$type": "Award",
    "id": "awd_usaspending_12",
    "piid": "N0002417C2117",
    "recipient": "ELECTRIC BOAT CORPORATION",
    "amount": 31078526826,
    "awardingAgency": "Department of Defense",
    "awardingSubAgency": "Department of the Navy",
    "startDate": "2017-09-21",
    "endDate": "2031-12-31",
    "description": "COLUMBIA CLASS DESIGN COMPLETION",
    "usaspendingId": "CONT_AWD_N0002417C2117_9700_-NONE-_-NONE-",
    "source": "USAspending",
    "real": true,
    "provenance": {
      "kind": "ingested",
      "source": "https://api.usaspending.gov/api/v2/search/spending_by_award/",
      "retrievedAt": "2026-08-23T19:27:20.542Z",
      "license": "U.S. government work — public domain (17 U.S.C. § 105)",
      "note": "REAL public federal contract award data ingested from USAspending. Not synthetic. Amounts and parties are as published by the source at retrievedAt; refresh via scripts/ingest-awards.mjs."
    }
  }
];
