/**
 * worker.js — public-admin, wave zero (register row public-admin, GAP at
 * apex; serving at the row-key placeholder address public-admin.org.ai).
 *
 * One substrate, two plies from ONE manifest (template spec §3): the data
 * face (/registrations, /filings, /awards, /permits — typed records from the
 * row's schemas, the Award corpus REAL and provenance-labeled) and the
 * headless face (the same collections as the entity back-office system door
 * at coordinate Compliance⟨registrant-back-office⟩, plus the per-outcome
 * renewal verb). There is no second API. The MCP door (/mcp) serves the same
 * operations from the same definitions.
 *
 * The AXP quartet + branching collection + conneg home are generated by the
 * vendored axp-faces (PINS.json digest) — never hand-rolled; the four
 * batch-2 ruled extension placements land in extensions.js. This file only
 * composes and adds the extra live doors the manifest declares.
 */

import { ok, empty, envelopeResponse, offer } from "./axp/index.js";
import { manifest, icpDoc } from "./manifest.js";
import { axpHandler } from "./extensions.js";
import { mcpHandler } from "./mcp.js";
import { filings, permits, getRegistration, getFiling, getPermit, EXAMPLE_NOTE } from "./seed.js";
import { awards, AWARDS_PROVENANCE } from "./seed-awards.js";
import { verifyRoutes } from "./verify.js";
import { emitMeter, emitReceipt, emitSignal } from "./seams.js";

const JSON_CT = { "content-type": "application/json; charset=utf-8" };

function json(obj, { status = 200, head = false } = {}) {
  return new Response(head ? null : JSON.stringify(obj, null, 2), { status, headers: JSON_CT });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const head = request.method === "HEAD";

    // ── the MCP door (same operations, second transport) ─────────────────────
    const mcpHit = await mcpHandler(request, env);
    if (mcpHit !== undefined) return mcpHit;

    // ── the machine face (extended card/openapi/pricing, then the generator) ──
    const hit = await axpHandler(request, env);
    if (hit !== undefined) {
      if (path === manifest.collection.path) emitMeter(env, { operation: "listRegistrations" });
      if (path === "/" || path === "/index.html") emitSignal(env, request, { surface: "home" });
      return hit;
    }

    // ── extra live doors (every one declared in the manifest routes) ─────────
    if (request.method === "GET" || head) {
      const regMatch = path.match(/^\/registrations\/([A-Za-z0-9_.-]+)$/);
      if (regMatch) {
        emitMeter(env, { operation: "getRegistration" });
        const registration = getRegistration(regMatch[1]);
        if (!registration)
          return json(empty(`no registration '${regMatch[1]}' is visible to this caller — an honest miss, not an error page`, { memberName: "registrations" }), { status: 404, head });
        return json({ type: "OK", registration }, { head });
      }

      if (path === "/filings") {
        emitMeter(env, { operation: "listFilings" });
        const status = url.searchParams.get("status");
        const rows = status ? filings.filter((f) => f.status === status) : filings;
        if (rows.length === 0) return json(empty(`no filings match status=${status} — a truthful empty set, not an error`, { memberName: "filings" }), { head });
        return json(ok(rows, { memberName: "filings" }), { head });
      }

      const filMatch = path.match(/^\/filings\/([A-Za-z0-9_.-]+)$/);
      if (filMatch) {
        emitMeter(env, { operation: "getFiling" });
        const filing = getFiling(filMatch[1]);
        if (!filing) return json(empty(`no filing '${filMatch[1]}' exists in this workspace`, { memberName: "filings" }), { status: 404, head });
        return json({ type: "OK", filing }, { head });
      }

      if (path === "/awards") {
        emitMeter(env, { operation: "listAwards" });
        return json(ok(awards, { memberName: "awards", extra: { provenance: AWARDS_PROVENANCE } }), { head });
      }

      const awdMatch = path.match(/^\/awards\/([A-Za-z0-9_.-]+)$/);
      if (awdMatch) {
        emitMeter(env, { operation: "getAward" });
        const award = awards.find((a) => a.id === awdMatch[1]);
        if (!award) return json(empty(`no award '${awdMatch[1]}' is in the ingested corpus — see /awards for the corpus and its provenance`, { memberName: "awards" }), { status: 404, head });
        return json({ type: "OK", award }, { head });
      }

      if (path === "/permits") {
        emitMeter(env, { operation: "listPermits" });
        return json(ok(permits, { memberName: "permits" }), { head });
      }

      const prmMatch = path.match(/^\/permits\/([A-Za-z0-9_.-]+)$/);
      if (prmMatch) {
        emitMeter(env, { operation: "getPermit" });
        const permit = getPermit(prmMatch[1]);
        if (!permit) return json(empty(`no permit '${prmMatch[1]}' exists in this workspace`, { memberName: "permits" }), { status: 404, head });
        return json({ type: "OK", permit }, { head });
      }

      if (path === "/icp.json") {
        // the G2 document the card's g2 member mirrors (links.icp / icpUrl)
        return json(icpDoc, { head });
      }

      if (path === "/healthz") return json(ok([{ status: "ok", sandbox: "anon", note: EXAMPLE_NOTE }]), { head });

      const v = await verifyRoutes(request, url);
      if (v !== undefined) return v;
    }

    // ── the per-outcome renewal door: a typed 402 OFFER; wave-zero labeled stub ──
    if (path === "/renewals" && request.method === "POST") {
      emitMeter(env, { operation: "orderRenewal", shape: "paid-402" });
      emitReceipt(env, { operation: "orderRenewal", offerId: "registration-renewal-outcome" });
      return envelopeResponse(
        offer({
          ...manifest.pricing.offers[0],
          message:
            "Ordering a completed registration renewal filing is the payable outcome door. Wave zero is " +
            "test-mode: this 402 is a labeled stub — no billing occurs. The alternatives list only mounted " +
            "rungs: the free keyless sandbox floor, or the pay rung (stub).",
        }),
        { status: 402 },
      );
    }

    return envelopeResponse(
      empty(`nothing is served at ${request.method} ${path} — the contract at /openapi.json lists every live door`),
      { status: 404 },
    );
  },
};
